// Code generated by ent, DO NOT EDIT.

package mailboxsyncstate

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldAccountID, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldKey, v))
}

// HighestUID applies equality check predicate on the "highest_uid" field. It's identical to HighestUIDEQ.
func HighestUID(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldHighestUID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldContainsFold(FieldAccountID, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldContainsFold(FieldKey, v))
}

// HighestUIDEQ applies the EQ predicate on the "highest_uid" field.
func HighestUIDEQ(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldEQ(FieldHighestUID, v))
}

// HighestUIDNEQ applies the NEQ predicate on the "highest_uid" field.
func HighestUIDNEQ(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNEQ(FieldHighestUID, v))
}

// HighestUIDIn applies the In predicate on the "highest_uid" field.
func HighestUIDIn(vs ...uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldIn(FieldHighestUID, vs...))
}

// HighestUIDNotIn applies the NotIn predicate on the "highest_uid" field.
func HighestUIDNotIn(vs ...uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldNotIn(FieldHighestUID, vs...))
}

// HighestUIDGT applies the GT predicate on the "highest_uid" field.
func HighestUIDGT(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGT(FieldHighestUID, v))
}

// HighestUIDGTE applies the GTE predicate on the "highest_uid" field.
func HighestUIDGTE(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldGTE(FieldHighestUID, v))
}

// HighestUIDLT applies the LT predicate on the "highest_uid" field.
func HighestUIDLT(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLT(FieldHighestUID, v))
}

// HighestUIDLTE applies the LTE predicate on the "highest_uid" field.
func HighestUIDLTE(v uint64) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.FieldLTE(FieldHighestUID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailboxSyncState) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailboxSyncState) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailboxSyncState) predicate.MailboxSyncState {
	return predicate.MailboxSyncState(sql.NotPredicates(p))
}
