// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/activitylog"
)

// ActivityLogCreate is the builder for creating a ActivityLog entity.
type ActivityLogCreate struct {
	config
	mutation *ActivityLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModule sets the "module" field.
func (_c *ActivityLogCreate) SetModule(v string) *ActivityLogCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ActivityLogCreate) SetAccountID(v string) *ActivityLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableAccountID(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *ActivityLogCreate) SetCategory(v string) *ActivityLogCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *ActivityLogCreate) SetAction(v string) *ActivityLogCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *ActivityLogCreate) SetLevel(v string) *ActivityLogCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *ActivityLogCreate) SetOutcome(v string) *ActivityLogCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *ActivityLogCreate) SetSummary(v string) *ActivityLogCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *ActivityLogCreate) SetSource(v string) *ActivityLogCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetMethod sets the "method" field.
func (_c *ActivityLogCreate) SetMethod(v string) *ActivityLogCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableMethod(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *ActivityLogCreate) SetPath(v string) *ActivityLogCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillablePath(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetHTTPStatus sets the "http_status" field.
func (_c *ActivityLogCreate) SetHTTPStatus(v int) *ActivityLogCreate {
	_c.mutation.SetHTTPStatus(v)
	return _c
}

// SetNillableHTTPStatus sets the "http_status" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableHTTPStatus(v *int) *ActivityLogCreate {
	if v != nil {
		_c.SetHTTPStatus(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *ActivityLogCreate) SetDurationMs(v int64) *ActivityLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableDurationMs(v *int64) *ActivityLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *ActivityLogCreate) SetRequestID(v string) *ActivityLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableRequestID(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *ActivityLogCreate) SetDetail(v string) *ActivityLogCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNillableDetail sets the "detail" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableDetail(v *string) *ActivityLogCreate {
	if v != nil {
		_c.SetDetail(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ActivityLogCreate) SetMetadata(v map[string]interface{}) *ActivityLogCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityLogCreate) SetCreatedAt(v time.Time) *ActivityLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableCreatedAt(v *time.Time) *ActivityLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ActivityLogMutation object of the builder.
func (_c *ActivityLogCreate) Mutation() *ActivityLogMutation {
	return _c.mutation
}

// Save creates the ActivityLog in the database.
func (_c *ActivityLogCreate) Save(ctx context.Context) (*ActivityLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityLogCreate) SaveX(ctx context.Context) *ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityLogCreate) defaults() {
	if _, ok := _c.mutation.AccountID(); !ok {
		v := activitylog.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := activitylog.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := activitylog.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.HTTPStatus(); !ok {
		v := activitylog.DefaultHTTPStatus
		_c.mutation.SetHTTPStatus(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := activitylog.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := activitylog.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.Detail(); !ok {
		v := activitylog.DefaultDetail
		_c.mutation.SetDetail(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := activitylog.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activitylog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityLogCreate) check() error {
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "ActivityLog.module"`)}
	}
	if v, ok := _c.mutation.Module(); ok {
		if err := activitylog.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ActivityLog.account_id"`)}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := activitylog.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "ActivityLog.category"`)}
	}
	if v, ok := _c.mutation.Category(); ok {
		if err := activitylog.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.category": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ActivityLog.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := activitylog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "ActivityLog.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := activitylog.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "ActivityLog.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := activitylog.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "ActivityLog.summary"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := activitylog.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ActivityLog.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := activitylog.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "ActivityLog.method"`)}
	}
	if v, ok := _c.mutation.Method(); ok {
		if err := activitylog.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "ActivityLog.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := activitylog.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTTPStatus(); !ok {
		return &ValidationError{Name: "http_status", err: errors.New(`ent: missing required field "ActivityLog.http_status"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "ActivityLog.duration_ms"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "ActivityLog.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := activitylog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Detail(); !ok {
		return &ValidationError{Name: "detail", err: errors.New(`ent: missing required field "ActivityLog.detail"`)}
	}
	if v, ok := _c.mutation.Detail(); ok {
		if err := activitylog.DetailValidator(v); err != nil {
			return &ValidationError{Name: "detail", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.detail": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "ActivityLog.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityLog.created_at"`)}
	}
	return nil
}

func (_c *ActivityLogCreate) sqlSave(ctx context.Context) (*ActivityLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityLogCreate) createSpec() (*ActivityLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activitylog.Table, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(activitylog.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(activitylog.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(activitylog.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(activitylog.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(activitylog.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(activitylog.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(activitylog.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(activitylog.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(activitylog.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(activitylog.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.HTTPStatus(); ok {
		_spec.SetField(activitylog.FieldHTTPStatus, field.TypeInt, value)
		_node.HTTPStatus = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(activitylog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(activitylog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(activitylog.FieldDetail, field.TypeString, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(activitylog.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activitylog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityLog.Create().
//		SetModule(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityLogUpsert) {
//			SetModule(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityLogCreate) OnConflict(opts ...sql.ConflictOption) *ActivityLogUpsertOne {
	_c.conflict = opts
	return &ActivityLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityLogCreate) OnConflictColumns(columns ...string) *ActivityLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityLogUpsertOne{
		create: _c,
	}
}

type (
	// ActivityLogUpsertOne is the builder for "upsert"-ing
	//  one ActivityLog node.
	ActivityLogUpsertOne struct {
		create *ActivityLogCreate
	}

	// ActivityLogUpsert is the "OnConflict" setter.
	ActivityLogUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivityLogUpsertOne) UpdateNewValues() *ActivityLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.Module(); exists {
			s.SetIgnore(activitylog.FieldModule)
		}
		if _, exists := u.create.mutation.AccountID(); exists {
			s.SetIgnore(activitylog.FieldAccountID)
		}
		if _, exists := u.create.mutation.Category(); exists {
			s.SetIgnore(activitylog.FieldCategory)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(activitylog.FieldAction)
		}
		if _, exists := u.create.mutation.Level(); exists {
			s.SetIgnore(activitylog.FieldLevel)
		}
		if _, exists := u.create.mutation.Outcome(); exists {
			s.SetIgnore(activitylog.FieldOutcome)
		}
		if _, exists := u.create.mutation.Summary(); exists {
			s.SetIgnore(activitylog.FieldSummary)
		}
		if _, exists := u.create.mutation.Source(); exists {
			s.SetIgnore(activitylog.FieldSource)
		}
		if _, exists := u.create.mutation.Method(); exists {
			s.SetIgnore(activitylog.FieldMethod)
		}
		if _, exists := u.create.mutation.Path(); exists {
			s.SetIgnore(activitylog.FieldPath)
		}
		if _, exists := u.create.mutation.HTTPStatus(); exists {
			s.SetIgnore(activitylog.FieldHTTPStatus)
		}
		if _, exists := u.create.mutation.DurationMs(); exists {
			s.SetIgnore(activitylog.FieldDurationMs)
		}
		if _, exists := u.create.mutation.RequestID(); exists {
			s.SetIgnore(activitylog.FieldRequestID)
		}
		if _, exists := u.create.mutation.Detail(); exists {
			s.SetIgnore(activitylog.FieldDetail)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(activitylog.FieldMetadata)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(activitylog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ActivityLogUpsertOne) Ignore() *ActivityLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityLogUpsertOne) DoNothing() *ActivityLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityLogCreate.OnConflict
// documentation for more info.
func (u *ActivityLogUpsertOne) Update(set func(*ActivityLogUpsert)) *ActivityLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityLogUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ActivityLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ActivityLogUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ActivityLogUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ActivityLogCreateBulk is the builder for creating many ActivityLog entities in bulk.
type ActivityLogCreateBulk struct {
	config
	err      error
	builders []*ActivityLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ActivityLog entities in the database.
func (_c *ActivityLogCreateBulk) Save(ctx context.Context) ([]*ActivityLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivityLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) SaveX(ctx context.Context) []*ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ActivityLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ActivityLogUpsert) {
//			SetModule(v+v).
//		}).
//		Exec(ctx)
func (_c *ActivityLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ActivityLogUpsertBulk {
	_c.conflict = opts
	return &ActivityLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ActivityLogCreateBulk) OnConflictColumns(columns ...string) *ActivityLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ActivityLogUpsertBulk{
		create: _c,
	}
}

// ActivityLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ActivityLog nodes.
type ActivityLogUpsertBulk struct {
	create *ActivityLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ActivityLogUpsertBulk) UpdateNewValues() *ActivityLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.Module(); exists {
				s.SetIgnore(activitylog.FieldModule)
			}
			if _, exists := b.mutation.AccountID(); exists {
				s.SetIgnore(activitylog.FieldAccountID)
			}
			if _, exists := b.mutation.Category(); exists {
				s.SetIgnore(activitylog.FieldCategory)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(activitylog.FieldAction)
			}
			if _, exists := b.mutation.Level(); exists {
				s.SetIgnore(activitylog.FieldLevel)
			}
			if _, exists := b.mutation.Outcome(); exists {
				s.SetIgnore(activitylog.FieldOutcome)
			}
			if _, exists := b.mutation.Summary(); exists {
				s.SetIgnore(activitylog.FieldSummary)
			}
			if _, exists := b.mutation.Source(); exists {
				s.SetIgnore(activitylog.FieldSource)
			}
			if _, exists := b.mutation.Method(); exists {
				s.SetIgnore(activitylog.FieldMethod)
			}
			if _, exists := b.mutation.Path(); exists {
				s.SetIgnore(activitylog.FieldPath)
			}
			if _, exists := b.mutation.HTTPStatus(); exists {
				s.SetIgnore(activitylog.FieldHTTPStatus)
			}
			if _, exists := b.mutation.DurationMs(); exists {
				s.SetIgnore(activitylog.FieldDurationMs)
			}
			if _, exists := b.mutation.RequestID(); exists {
				s.SetIgnore(activitylog.FieldRequestID)
			}
			if _, exists := b.mutation.Detail(); exists {
				s.SetIgnore(activitylog.FieldDetail)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(activitylog.FieldMetadata)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(activitylog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ActivityLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ActivityLogUpsertBulk) Ignore() *ActivityLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ActivityLogUpsertBulk) DoNothing() *ActivityLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ActivityLogCreateBulk.OnConflict
// documentation for more info.
func (u *ActivityLogUpsertBulk) Update(set func(*ActivityLogUpsert)) *ActivityLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ActivityLogUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ActivityLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ActivityLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ActivityLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ActivityLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
