// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authuser"
)

// AuthUserCreate is the builder for creating a AuthUser entity.
type AuthUserCreate struct {
	config
	mutation *AuthUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsername sets the "username" field.
func (_c *AuthUserCreate) SetUsername(v string) *AuthUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPasswordHash sets the "password_hash" field.
func (_c *AuthUserCreate) SetPasswordHash(v string) *AuthUserCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetMustChangePassword sets the "must_change_password" field.
func (_c *AuthUserCreate) SetMustChangePassword(v bool) *AuthUserCreate {
	_c.mutation.SetMustChangePassword(v)
	return _c
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_c *AuthUserCreate) SetNillableMustChangePassword(v *bool) *AuthUserCreate {
	if v != nil {
		_c.SetMustChangePassword(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *AuthUserCreate) SetDisabled(v bool) *AuthUserCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *AuthUserCreate) SetNillableDisabled(v *bool) *AuthUserCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthUserCreate) SetCreatedAt(v time.Time) *AuthUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthUserCreate) SetNillableCreatedAt(v *time.Time) *AuthUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AuthUserCreate) SetUpdatedAt(v time.Time) *AuthUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AuthUserCreate) SetNillableUpdatedAt(v *time.Time) *AuthUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetLastLoginAt sets the "last_login_at" field.
func (_c *AuthUserCreate) SetLastLoginAt(v time.Time) *AuthUserCreate {
	_c.mutation.SetLastLoginAt(v)
	return _c
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_c *AuthUserCreate) SetNillableLastLoginAt(v *time.Time) *AuthUserCreate {
	if v != nil {
		_c.SetLastLoginAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthUserCreate) SetID(v int64) *AuthUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthUserMutation object of the builder.
func (_c *AuthUserCreate) Mutation() *AuthUserMutation {
	return _c.mutation
}

// Save creates the AuthUser in the database.
func (_c *AuthUserCreate) Save(ctx context.Context) (*AuthUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthUserCreate) SaveX(ctx context.Context) *AuthUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthUserCreate) defaults() {
	if _, ok := _c.mutation.MustChangePassword(); !ok {
		v := authuser.DefaultMustChangePassword
		_c.mutation.SetMustChangePassword(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := authuser.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := authuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthUserCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AuthUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := authuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AuthUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "AuthUser.password_hash"`)}
	}
	if _, ok := _c.mutation.MustChangePassword(); !ok {
		return &ValidationError{Name: "must_change_password", err: errors.New(`ent: missing required field "AuthUser.must_change_password"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "AuthUser.disabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AuthUser.updated_at"`)}
	}
	return nil
}

func (_c *AuthUserCreate) sqlSave(ctx context.Context) (*AuthUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthUserCreate) createSpec() (*AuthUser, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authuser.Table, sqlgraph.NewFieldSpec(authuser.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(authuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(authuser.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.MustChangePassword(); ok {
		_spec.SetField(authuser.FieldMustChangePassword, field.TypeBool, value)
		_node.MustChangePassword = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(authuser.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(authuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LastLoginAt(); ok {
		_spec.SetField(authuser.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthUser.Create().
//		SetUsername(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthUserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthUserCreate) OnConflict(opts ...sql.ConflictOption) *AuthUserUpsertOne {
	_c.conflict = opts
	return &AuthUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthUserCreate) OnConflictColumns(columns ...string) *AuthUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthUserUpsertOne{
		create: _c,
	}
}

type (
	// AuthUserUpsertOne is the builder for "upsert"-ing
	//  one AuthUser node.
	AuthUserUpsertOne struct {
		create *AuthUserCreate
	}

	// AuthUserUpsert is the "OnConflict" setter.
	AuthUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsername sets the "username" field.
func (u *AuthUserUpsert) SetUsername(v string) *AuthUserUpsert {
	u.Set(authuser.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdateUsername() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldUsername)
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthUserUpsert) SetPasswordHash(v string) *AuthUserUpsert {
	u.Set(authuser.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdatePasswordHash() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldPasswordHash)
	return u
}

// SetMustChangePassword sets the "must_change_password" field.
func (u *AuthUserUpsert) SetMustChangePassword(v bool) *AuthUserUpsert {
	u.Set(authuser.FieldMustChangePassword, v)
	return u
}

// UpdateMustChangePassword sets the "must_change_password" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdateMustChangePassword() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldMustChangePassword)
	return u
}

// SetDisabled sets the "disabled" field.
func (u *AuthUserUpsert) SetDisabled(v bool) *AuthUserUpsert {
	u.Set(authuser.FieldDisabled, v)
	return u
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdateDisabled() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldDisabled)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUserUpsert) SetUpdatedAt(v time.Time) *AuthUserUpsert {
	u.Set(authuser.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdateUpdatedAt() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldUpdatedAt)
	return u
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *AuthUserUpsert) SetLastLoginAt(v time.Time) *AuthUserUpsert {
	u.Set(authuser.FieldLastLoginAt, v)
	return u
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *AuthUserUpsert) UpdateLastLoginAt() *AuthUserUpsert {
	u.SetExcluded(authuser.FieldLastLoginAt)
	return u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *AuthUserUpsert) ClearLastLoginAt() *AuthUserUpsert {
	u.SetNull(authuser.FieldLastLoginAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authuser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthUserUpsertOne) UpdateNewValues() *AuthUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authuser.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthUserUpsertOne) Ignore() *AuthUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthUserUpsertOne) DoNothing() *AuthUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthUserCreate.OnConflict
// documentation for more info.
func (u *AuthUserUpsertOne) Update(set func(*AuthUserUpsert)) *AuthUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *AuthUserUpsertOne) SetUsername(v string) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdateUsername() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateUsername()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthUserUpsertOne) SetPasswordHash(v string) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdatePasswordHash() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetMustChangePassword sets the "must_change_password" field.
func (u *AuthUserUpsertOne) SetMustChangePassword(v bool) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetMustChangePassword(v)
	})
}

// UpdateMustChangePassword sets the "must_change_password" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdateMustChangePassword() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateMustChangePassword()
	})
}

// SetDisabled sets the "disabled" field.
func (u *AuthUserUpsertOne) SetDisabled(v bool) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdateDisabled() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateDisabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUserUpsertOne) SetUpdatedAt(v time.Time) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdateUpdatedAt() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *AuthUserUpsertOne) SetLastLoginAt(v time.Time) *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *AuthUserUpsertOne) UpdateLastLoginAt() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *AuthUserUpsertOne) ClearLastLoginAt() *AuthUserUpsertOne {
	return u.Update(func(s *AuthUserUpsert) {
		s.ClearLastLoginAt()
	})
}

// Exec executes the query.
func (u *AuthUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthUserUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthUserUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthUserCreateBulk is the builder for creating many AuthUser entities in bulk.
type AuthUserCreateBulk struct {
	config
	err      error
	builders []*AuthUserCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthUser entities in the database.
func (_c *AuthUserCreateBulk) Save(ctx context.Context) ([]*AuthUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthUserCreateBulk) SaveX(ctx context.Context) []*AuthUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthUserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthUserUpsertBulk {
	_c.conflict = opts
	return &AuthUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthUserCreateBulk) OnConflictColumns(columns ...string) *AuthUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthUserUpsertBulk{
		create: _c,
	}
}

// AuthUserUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthUser nodes.
type AuthUserUpsertBulk struct {
	create *AuthUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authuser.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthUserUpsertBulk) UpdateNewValues() *AuthUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authuser.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthUserUpsertBulk) Ignore() *AuthUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthUserUpsertBulk) DoNothing() *AuthUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthUserCreateBulk.OnConflict
// documentation for more info.
func (u *AuthUserUpsertBulk) Update(set func(*AuthUserUpsert)) *AuthUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *AuthUserUpsertBulk) SetUsername(v string) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdateUsername() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateUsername()
	})
}

// SetPasswordHash sets the "password_hash" field.
func (u *AuthUserUpsertBulk) SetPasswordHash(v string) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdatePasswordHash() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetMustChangePassword sets the "must_change_password" field.
func (u *AuthUserUpsertBulk) SetMustChangePassword(v bool) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetMustChangePassword(v)
	})
}

// UpdateMustChangePassword sets the "must_change_password" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdateMustChangePassword() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateMustChangePassword()
	})
}

// SetDisabled sets the "disabled" field.
func (u *AuthUserUpsertBulk) SetDisabled(v bool) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetDisabled(v)
	})
}

// UpdateDisabled sets the "disabled" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdateDisabled() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateDisabled()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AuthUserUpsertBulk) SetUpdatedAt(v time.Time) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdateUpdatedAt() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *AuthUserUpsertBulk) SetLastLoginAt(v time.Time) *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *AuthUserUpsertBulk) UpdateLastLoginAt() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *AuthUserUpsertBulk) ClearLastLoginAt() *AuthUserUpsertBulk {
	return u.Update(func(s *AuthUserUpsert) {
		s.ClearLastLoginAt()
	})
}

// Exec executes the query.
func (u *AuthUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
