// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authapitoken"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// AuthAPITokenUpdate is the builder for updating AuthAPIToken entities.
type AuthAPITokenUpdate struct {
	config
	hooks    []Hook
	mutation *AuthAPITokenMutation
}

// Where appends a list predicates to the AuthAPITokenUpdate builder.
func (_u *AuthAPITokenUpdate) Where(ps ...predicate.AuthAPIToken) *AuthAPITokenUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *AuthAPITokenUpdate) SetName(v string) *AuthAPITokenUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuthAPITokenUpdate) SetNillableName(v *string) *AuthAPITokenUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AuthAPITokenUpdate) SetLastUsedAt(v time.Time) *AuthAPITokenUpdate {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdate) SetNillableLastUsedAt(v *time.Time) *AuthAPITokenUpdate {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AuthAPITokenUpdate) ClearLastUsedAt() *AuthAPITokenUpdate {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthAPITokenUpdate) SetExpiresAt(v time.Time) *AuthAPITokenUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdate) SetNillableExpiresAt(v *time.Time) *AuthAPITokenUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AuthAPITokenUpdate) ClearExpiresAt() *AuthAPITokenUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthAPITokenUpdate) SetRevokedAt(v time.Time) *AuthAPITokenUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdate) SetNillableRevokedAt(v *time.Time) *AuthAPITokenUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthAPITokenUpdate) ClearRevokedAt() *AuthAPITokenUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AuthAPITokenMutation object of the builder.
func (_u *AuthAPITokenUpdate) Mutation() *AuthAPITokenMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthAPITokenUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAPITokenUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthAPITokenUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAPITokenUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthAPITokenUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := authapitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AuthAPIToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthAPITokenUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authapitoken.Table, authapitoken.Columns, sqlgraph.NewFieldSpec(authapitoken.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(authapitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(authapitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(authapitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authapitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(authapitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authapitoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authapitoken.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authapitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthAPITokenUpdateOne is the builder for updating a single AuthAPIToken entity.
type AuthAPITokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthAPITokenMutation
}

// SetName sets the "name" field.
func (_u *AuthAPITokenUpdateOne) SetName(v string) *AuthAPITokenUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AuthAPITokenUpdateOne) SetNillableName(v *string) *AuthAPITokenUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLastUsedAt sets the "last_used_at" field.
func (_u *AuthAPITokenUpdateOne) SetLastUsedAt(v time.Time) *AuthAPITokenUpdateOne {
	_u.mutation.SetLastUsedAt(v)
	return _u
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdateOne) SetNillableLastUsedAt(v *time.Time) *AuthAPITokenUpdateOne {
	if v != nil {
		_u.SetLastUsedAt(*v)
	}
	return _u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (_u *AuthAPITokenUpdateOne) ClearLastUsedAt() *AuthAPITokenUpdateOne {
	_u.mutation.ClearLastUsedAt()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthAPITokenUpdateOne) SetExpiresAt(v time.Time) *AuthAPITokenUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthAPITokenUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *AuthAPITokenUpdateOne) ClearExpiresAt() *AuthAPITokenUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *AuthAPITokenUpdateOne) SetRevokedAt(v time.Time) *AuthAPITokenUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *AuthAPITokenUpdateOne) SetNillableRevokedAt(v *time.Time) *AuthAPITokenUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *AuthAPITokenUpdateOne) ClearRevokedAt() *AuthAPITokenUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the AuthAPITokenMutation object of the builder.
func (_u *AuthAPITokenUpdateOne) Mutation() *AuthAPITokenMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthAPITokenUpdate builder.
func (_u *AuthAPITokenUpdateOne) Where(ps ...predicate.AuthAPIToken) *AuthAPITokenUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthAPITokenUpdateOne) Select(field string, fields ...string) *AuthAPITokenUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthAPIToken entity.
func (_u *AuthAPITokenUpdateOne) Save(ctx context.Context) (*AuthAPIToken, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAPITokenUpdateOne) SaveX(ctx context.Context) *AuthAPIToken {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthAPITokenUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAPITokenUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthAPITokenUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := authapitoken.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AuthAPIToken.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthAPITokenUpdateOne) sqlSave(ctx context.Context) (_node *AuthAPIToken, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authapitoken.Table, authapitoken.Columns, sqlgraph.NewFieldSpec(authapitoken.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthAPIToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authapitoken.FieldID)
		for _, f := range fields {
			if !authapitoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authapitoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(authapitoken.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUsedAt(); ok {
		_spec.SetField(authapitoken.FieldLastUsedAt, field.TypeTime, value)
	}
	if _u.mutation.LastUsedAtCleared() {
		_spec.ClearField(authapitoken.FieldLastUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authapitoken.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(authapitoken.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(authapitoken.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(authapitoken.FieldRevokedAt, field.TypeTime)
	}
	_node = &AuthAPIToken{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authapitoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
