// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authsession"
)

// AuthSessionCreate is the builder for creating a AuthSession entity.
type AuthSessionCreate struct {
	config
	mutation *AuthSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *AuthSessionCreate) SetUserID(v int64) *AuthSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *AuthSessionCreate) SetIPAddress(v string) *AuthSessionCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableIPAddress(v *string) *AuthSessionCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AuthSessionCreate) SetUserAgent(v string) *AuthSessionCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableUserAgent(v *string) *AuthSessionCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthSessionCreate) SetCreatedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableCreatedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *AuthSessionCreate) SetLastSeenAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableLastSeenAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetLastSeenAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AuthSessionCreate) SetExpiresAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *AuthSessionCreate) SetRevokedAt(v time.Time) *AuthSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *AuthSessionCreate) SetNillableRevokedAt(v *time.Time) *AuthSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthSessionCreate) SetID(v string) *AuthSessionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthSessionMutation object of the builder.
func (_c *AuthSessionCreate) Mutation() *AuthSessionMutation {
	return _c.mutation
}

// Save creates the AuthSession in the database.
func (_c *AuthSessionCreate) Save(ctx context.Context) (*AuthSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthSessionCreate) SaveX(ctx context.Context) *AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthSessionCreate) defaults() {
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := authsession.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := authsession.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		v := authsession.DefaultLastSeenAt()
		_c.mutation.SetLastSeenAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthSessionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "AuthSession.user_id"`)}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "AuthSession.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := authsession.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuthSession.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "AuthSession.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := authsession.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuthSession.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthSession.created_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "AuthSession.last_seen_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AuthSession.expires_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := authsession.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AuthSession.id": %w`, err)}
		}
	}
	return nil
}

func (_c *AuthSessionCreate) sqlSave(ctx context.Context) (*AuthSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuthSession.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthSessionCreate) createSpec() (*AuthSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authsession.Table, sqlgraph.NewFieldSpec(authsession.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(authsession.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(authsession.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(authsession.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(authsession.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(authsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(authsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSession.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSessionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSessionCreate) OnConflict(opts ...sql.ConflictOption) *AuthSessionUpsertOne {
	_c.conflict = opts
	return &AuthSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSessionCreate) OnConflictColumns(columns ...string) *AuthSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSessionUpsertOne{
		create: _c,
	}
}

type (
	// AuthSessionUpsertOne is the builder for "upsert"-ing
	//  one AuthSession node.
	AuthSessionUpsertOne struct {
		create *AuthSessionCreate
	}

	// AuthSessionUpsert is the "OnConflict" setter.
	AuthSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsert) SetLastSeenAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateLastSeenAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldLastSeenAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsert) SetRevokedAt(v time.Time) *AuthSessionUpsert {
	u.Set(authsession.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsert) UpdateRevokedAt() *AuthSessionUpsert {
	u.SetExcluded(authsession.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsert) ClearRevokedAt() *AuthSessionUpsert {
	u.SetNull(authsession.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSessionUpsertOne) UpdateNewValues() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authsession.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(authsession.FieldUserID)
		}
		if _, exists := u.create.mutation.IPAddress(); exists {
			s.SetIgnore(authsession.FieldIPAddress)
		}
		if _, exists := u.create.mutation.UserAgent(); exists {
			s.SetIgnore(authsession.FieldUserAgent)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authsession.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(authsession.FieldExpiresAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthSessionUpsertOne) Ignore() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSessionUpsertOne) DoNothing() *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSessionCreate.OnConflict
// documentation for more info.
func (u *AuthSessionUpsertOne) Update(set func(*AuthSessionUpsert)) *AuthSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsertOne) SetLastSeenAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateLastSeenAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsertOne) SetRevokedAt(v time.Time) *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsertOne) UpdateRevokedAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsertOne) ClearRevokedAt() *AuthSessionUpsertOne {
	return u.Update(func(s *AuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AuthSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthSessionUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuthSessionUpsertOne.ID is not supported by MySQL driver. Use AuthSessionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthSessionUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthSessionCreateBulk is the builder for creating many AuthSession entities in bulk.
type AuthSessionCreateBulk struct {
	config
	err      error
	builders []*AuthSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthSession entities in the database.
func (_c *AuthSessionCreateBulk) Save(ctx context.Context) ([]*AuthSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) SaveX(ctx context.Context) []*AuthSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthSessionUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthSessionUpsertBulk {
	_c.conflict = opts
	return &AuthSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthSessionCreateBulk) OnConflictColumns(columns ...string) *AuthSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthSessionUpsertBulk{
		create: _c,
	}
}

// AuthSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthSession nodes.
type AuthSessionUpsertBulk struct {
	create *AuthSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authsession.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthSessionUpsertBulk) UpdateNewValues() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authsession.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(authsession.FieldUserID)
			}
			if _, exists := b.mutation.IPAddress(); exists {
				s.SetIgnore(authsession.FieldIPAddress)
			}
			if _, exists := b.mutation.UserAgent(); exists {
				s.SetIgnore(authsession.FieldUserAgent)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authsession.FieldCreatedAt)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(authsession.FieldExpiresAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthSessionUpsertBulk) Ignore() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthSessionUpsertBulk) DoNothing() *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthSessionCreateBulk.OnConflict
// documentation for more info.
func (u *AuthSessionUpsertBulk) Update(set func(*AuthSessionUpsert)) *AuthSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *AuthSessionUpsertBulk) SetLastSeenAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateLastSeenAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *AuthSessionUpsertBulk) SetRevokedAt(v time.Time) *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *AuthSessionUpsertBulk) UpdateRevokedAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *AuthSessionUpsertBulk) ClearRevokedAt() *AuthSessionUpsertBulk {
	return u.Update(func(s *AuthSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *AuthSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
