// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authloginevent"
)

// AuthLoginEventCreate is the builder for creating a AuthLoginEvent entity.
type AuthLoginEventCreate struct {
	config
	mutation *AuthLoginEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *AuthLoginEventCreate) SetUserID(v int64) *AuthLoginEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AuthLoginEventCreate) SetNillableUserID(v *int64) *AuthLoginEventCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *AuthLoginEventCreate) SetUsername(v string) *AuthLoginEventCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *AuthLoginEventCreate) SetOutcome(v string) *AuthLoginEventCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *AuthLoginEventCreate) SetReason(v string) *AuthLoginEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *AuthLoginEventCreate) SetNillableReason(v *string) *AuthLoginEventCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetIPAddress sets the "ip_address" field.
func (_c *AuthLoginEventCreate) SetIPAddress(v string) *AuthLoginEventCreate {
	_c.mutation.SetIPAddress(v)
	return _c
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_c *AuthLoginEventCreate) SetNillableIPAddress(v *string) *AuthLoginEventCreate {
	if v != nil {
		_c.SetIPAddress(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *AuthLoginEventCreate) SetUserAgent(v string) *AuthLoginEventCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *AuthLoginEventCreate) SetNillableUserAgent(v *string) *AuthLoginEventCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuthLoginEventCreate) SetCreatedAt(v time.Time) *AuthLoginEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuthLoginEventCreate) SetNillableCreatedAt(v *time.Time) *AuthLoginEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuthLoginEventCreate) SetID(v int64) *AuthLoginEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuthLoginEventMutation object of the builder.
func (_c *AuthLoginEventCreate) Mutation() *AuthLoginEventMutation {
	return _c.mutation
}

// Save creates the AuthLoginEvent in the database.
func (_c *AuthLoginEventCreate) Save(ctx context.Context) (*AuthLoginEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuthLoginEventCreate) SaveX(ctx context.Context) *AuthLoginEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthLoginEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthLoginEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuthLoginEventCreate) defaults() {
	if _, ok := _c.mutation.Reason(); !ok {
		v := authloginevent.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		v := authloginevent.DefaultIPAddress
		_c.mutation.SetIPAddress(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := authloginevent.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := authloginevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuthLoginEventCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AuthLoginEvent.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := authloginevent.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AuthLoginEvent.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "AuthLoginEvent.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := authloginevent.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "AuthLoginEvent.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "AuthLoginEvent.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := authloginevent.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "AuthLoginEvent.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IPAddress(); !ok {
		return &ValidationError{Name: "ip_address", err: errors.New(`ent: missing required field "AuthLoginEvent.ip_address"`)}
	}
	if v, ok := _c.mutation.IPAddress(); ok {
		if err := authloginevent.IPAddressValidator(v); err != nil {
			return &ValidationError{Name: "ip_address", err: fmt.Errorf(`ent: validator failed for field "AuthLoginEvent.ip_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "AuthLoginEvent.user_agent"`)}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := authloginevent.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AuthLoginEvent.user_agent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuthLoginEvent.created_at"`)}
	}
	return nil
}

func (_c *AuthLoginEventCreate) sqlSave(ctx context.Context) (*AuthLoginEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuthLoginEventCreate) createSpec() (*AuthLoginEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuthLoginEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(authloginevent.Table, sqlgraph.NewFieldSpec(authloginevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(authloginevent.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(authloginevent.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(authloginevent.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(authloginevent.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.IPAddress(); ok {
		_spec.SetField(authloginevent.FieldIPAddress, field.TypeString, value)
		_node.IPAddress = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(authloginevent.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(authloginevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthLoginEvent.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthLoginEventUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthLoginEventCreate) OnConflict(opts ...sql.ConflictOption) *AuthLoginEventUpsertOne {
	_c.conflict = opts
	return &AuthLoginEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthLoginEventCreate) OnConflictColumns(columns ...string) *AuthLoginEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthLoginEventUpsertOne{
		create: _c,
	}
}

type (
	// AuthLoginEventUpsertOne is the builder for "upsert"-ing
	//  one AuthLoginEvent node.
	AuthLoginEventUpsertOne struct {
		create *AuthLoginEventCreate
	}

	// AuthLoginEventUpsert is the "OnConflict" setter.
	AuthLoginEventUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authloginevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthLoginEventUpsertOne) UpdateNewValues() *AuthLoginEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(authloginevent.FieldID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(authloginevent.FieldUserID)
		}
		if _, exists := u.create.mutation.Username(); exists {
			s.SetIgnore(authloginevent.FieldUsername)
		}
		if _, exists := u.create.mutation.Outcome(); exists {
			s.SetIgnore(authloginevent.FieldOutcome)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(authloginevent.FieldReason)
		}
		if _, exists := u.create.mutation.IPAddress(); exists {
			s.SetIgnore(authloginevent.FieldIPAddress)
		}
		if _, exists := u.create.mutation.UserAgent(); exists {
			s.SetIgnore(authloginevent.FieldUserAgent)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(authloginevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuthLoginEventUpsertOne) Ignore() *AuthLoginEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthLoginEventUpsertOne) DoNothing() *AuthLoginEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthLoginEventCreate.OnConflict
// documentation for more info.
func (u *AuthLoginEventUpsertOne) Update(set func(*AuthLoginEventUpsert)) *AuthLoginEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthLoginEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuthLoginEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthLoginEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthLoginEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuthLoginEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuthLoginEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuthLoginEventCreateBulk is the builder for creating many AuthLoginEvent entities in bulk.
type AuthLoginEventCreateBulk struct {
	config
	err      error
	builders []*AuthLoginEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AuthLoginEvent entities in the database.
func (_c *AuthLoginEventCreateBulk) Save(ctx context.Context) ([]*AuthLoginEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuthLoginEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthLoginEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuthLoginEventCreateBulk) SaveX(ctx context.Context) []*AuthLoginEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuthLoginEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuthLoginEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuthLoginEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuthLoginEventUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *AuthLoginEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuthLoginEventUpsertBulk {
	_c.conflict = opts
	return &AuthLoginEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuthLoginEventCreateBulk) OnConflictColumns(columns ...string) *AuthLoginEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuthLoginEventUpsertBulk{
		create: _c,
	}
}

// AuthLoginEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AuthLoginEvent nodes.
type AuthLoginEventUpsertBulk struct {
	create *AuthLoginEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(authloginevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuthLoginEventUpsertBulk) UpdateNewValues() *AuthLoginEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(authloginevent.FieldID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(authloginevent.FieldUserID)
			}
			if _, exists := b.mutation.Username(); exists {
				s.SetIgnore(authloginevent.FieldUsername)
			}
			if _, exists := b.mutation.Outcome(); exists {
				s.SetIgnore(authloginevent.FieldOutcome)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(authloginevent.FieldReason)
			}
			if _, exists := b.mutation.IPAddress(); exists {
				s.SetIgnore(authloginevent.FieldIPAddress)
			}
			if _, exists := b.mutation.UserAgent(); exists {
				s.SetIgnore(authloginevent.FieldUserAgent)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(authloginevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuthLoginEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuthLoginEventUpsertBulk) Ignore() *AuthLoginEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuthLoginEventUpsertBulk) DoNothing() *AuthLoginEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuthLoginEventCreateBulk.OnConflict
// documentation for more info.
func (u *AuthLoginEventUpsertBulk) Update(set func(*AuthLoginEventUpsert)) *AuthLoginEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuthLoginEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuthLoginEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuthLoginEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuthLoginEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuthLoginEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
