// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authuser"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// AuthUserUpdate is the builder for updating AuthUser entities.
type AuthUserUpdate struct {
	config
	hooks    []Hook
	mutation *AuthUserMutation
}

// Where appends a list predicates to the AuthUserUpdate builder.
func (_u *AuthUserUpdate) Where(ps ...predicate.AuthUser) *AuthUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *AuthUserUpdate) SetUsername(v string) *AuthUserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableUsername(v *string) *AuthUserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AuthUserUpdate) SetPasswordHash(v string) *AuthUserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillablePasswordHash(v *string) *AuthUserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetMustChangePassword sets the "must_change_password" field.
func (_u *AuthUserUpdate) SetMustChangePassword(v bool) *AuthUserUpdate {
	_u.mutation.SetMustChangePassword(v)
	return _u
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableMustChangePassword(v *bool) *AuthUserUpdate {
	if v != nil {
		_u.SetMustChangePassword(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *AuthUserUpdate) SetDisabled(v bool) *AuthUserUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableDisabled(v *bool) *AuthUserUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthUserUpdate) SetUpdatedAt(v time.Time) *AuthUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *AuthUserUpdate) SetLastLoginAt(v time.Time) *AuthUserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *AuthUserUpdate) SetNillableLastLoginAt(v *time.Time) *AuthUserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *AuthUserUpdate) ClearLastLoginAt() *AuthUserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the AuthUserMutation object of the builder.
func (_u *AuthUserUpdate) Mutation() *AuthUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthUserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := authuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AuthUser.username": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authuser.Table, authuser.Columns, sqlgraph.NewFieldSpec(authuser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(authuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(authuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MustChangePassword(); ok {
		_spec.SetField(authuser.FieldMustChangePassword, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(authuser.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(authuser.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(authuser.FieldLastLoginAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthUserUpdateOne is the builder for updating a single AuthUser entity.
type AuthUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthUserMutation
}

// SetUsername sets the "username" field.
func (_u *AuthUserUpdateOne) SetUsername(v string) *AuthUserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableUsername(v *string) *AuthUserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *AuthUserUpdateOne) SetPasswordHash(v string) *AuthUserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillablePasswordHash(v *string) *AuthUserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetMustChangePassword sets the "must_change_password" field.
func (_u *AuthUserUpdateOne) SetMustChangePassword(v bool) *AuthUserUpdateOne {
	_u.mutation.SetMustChangePassword(v)
	return _u
}

// SetNillableMustChangePassword sets the "must_change_password" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableMustChangePassword(v *bool) *AuthUserUpdateOne {
	if v != nil {
		_u.SetMustChangePassword(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *AuthUserUpdateOne) SetDisabled(v bool) *AuthUserUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableDisabled(v *bool) *AuthUserUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthUserUpdateOne) SetUpdatedAt(v time.Time) *AuthUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *AuthUserUpdateOne) SetLastLoginAt(v time.Time) *AuthUserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *AuthUserUpdateOne) SetNillableLastLoginAt(v *time.Time) *AuthUserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *AuthUserUpdateOne) ClearLastLoginAt() *AuthUserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// Mutation returns the AuthUserMutation object of the builder.
func (_u *AuthUserUpdateOne) Mutation() *AuthUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthUserUpdate builder.
func (_u *AuthUserUpdateOne) Where(ps ...predicate.AuthUser) *AuthUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthUserUpdateOne) Select(field string, fields ...string) *AuthUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthUser entity.
func (_u *AuthUserUpdateOne) Save(ctx context.Context) (*AuthUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthUserUpdateOne) SaveX(ctx context.Context) *AuthUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthUserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := authuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AuthUser.username": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthUserUpdateOne) sqlSave(ctx context.Context) (_node *AuthUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authuser.Table, authuser.Columns, sqlgraph.NewFieldSpec(authuser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authuser.FieldID)
		for _, f := range fields {
			if !authuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(authuser.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(authuser.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.MustChangePassword(); ok {
		_spec.SetField(authuser.FieldMustChangePassword, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(authuser.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(authuser.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(authuser.FieldLastLoginAt, field.TypeTime)
	}
	_node = &AuthUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
