// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authloginevent"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// AuthLoginEventUpdate is the builder for updating AuthLoginEvent entities.
type AuthLoginEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuthLoginEventMutation
}

// Where appends a list predicates to the AuthLoginEventUpdate builder.
func (_u *AuthLoginEventUpdate) Where(ps ...predicate.AuthLoginEvent) *AuthLoginEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the AuthLoginEventMutation object of the builder.
func (_u *AuthLoginEventUpdate) Mutation() *AuthLoginEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthLoginEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthLoginEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthLoginEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthLoginEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthLoginEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authloginevent.Table, authloginevent.Columns, sqlgraph.NewFieldSpec(authloginevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authloginevent.FieldUserID, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authloginevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthLoginEventUpdateOne is the builder for updating a single AuthLoginEvent entity.
type AuthLoginEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthLoginEventMutation
}

// Mutation returns the AuthLoginEventMutation object of the builder.
func (_u *AuthLoginEventUpdateOne) Mutation() *AuthLoginEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthLoginEventUpdate builder.
func (_u *AuthLoginEventUpdateOne) Where(ps ...predicate.AuthLoginEvent) *AuthLoginEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthLoginEventUpdateOne) Select(field string, fields ...string) *AuthLoginEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthLoginEvent entity.
func (_u *AuthLoginEventUpdateOne) Save(ctx context.Context) (*AuthLoginEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthLoginEventUpdateOne) SaveX(ctx context.Context) *AuthLoginEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthLoginEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthLoginEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *AuthLoginEventUpdateOne) sqlSave(ctx context.Context) (_node *AuthLoginEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(authloginevent.Table, authloginevent.Columns, sqlgraph.NewFieldSpec(authloginevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthLoginEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authloginevent.FieldID)
		for _, f := range fields {
			if !authloginevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authloginevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(authloginevent.FieldUserID, field.TypeInt64)
	}
	_node = &AuthLoginEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authloginevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
