// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxhiddenmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxsyncstate"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MailboxHiddenMessage is the client for interacting with the MailboxHiddenMessage builders.
	MailboxHiddenMessage *MailboxHiddenMessageClient
	// MailboxMessage is the client for interacting with the MailboxMessage builders.
	MailboxMessage *MailboxMessageClient
	// MailboxSyncState is the client for interacting with the MailboxSyncState builders.
	MailboxSyncState *MailboxSyncStateClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MailboxHiddenMessage = NewMailboxHiddenMessageClient(c.config)
	c.MailboxMessage = NewMailboxMessageClient(c.config)
	c.MailboxSyncState = NewMailboxSyncStateClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		MailboxHiddenMessage: NewMailboxHiddenMessageClient(cfg),
		MailboxMessage:       NewMailboxMessageClient(cfg),
		MailboxSyncState:     NewMailboxSyncStateClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                  ctx,
		config:               cfg,
		MailboxHiddenMessage: NewMailboxHiddenMessageClient(cfg),
		MailboxMessage:       NewMailboxMessageClient(cfg),
		MailboxSyncState:     NewMailboxSyncStateClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MailboxHiddenMessage.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MailboxHiddenMessage.Use(hooks...)
	c.MailboxMessage.Use(hooks...)
	c.MailboxSyncState.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.MailboxHiddenMessage.Intercept(interceptors...)
	c.MailboxMessage.Intercept(interceptors...)
	c.MailboxSyncState.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *MailboxHiddenMessageMutation:
		return c.MailboxHiddenMessage.mutate(ctx, m)
	case *MailboxMessageMutation:
		return c.MailboxMessage.mutate(ctx, m)
	case *MailboxSyncStateMutation:
		return c.MailboxSyncState.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// MailboxHiddenMessageClient is a client for the MailboxHiddenMessage schema.
type MailboxHiddenMessageClient struct {
	config
}

// NewMailboxHiddenMessageClient returns a client for the MailboxHiddenMessage from the given config.
func NewMailboxHiddenMessageClient(c config) *MailboxHiddenMessageClient {
	return &MailboxHiddenMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mailboxhiddenmessage.Hooks(f(g(h())))`.
func (c *MailboxHiddenMessageClient) Use(hooks ...Hook) {
	c.hooks.MailboxHiddenMessage = append(c.hooks.MailboxHiddenMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mailboxhiddenmessage.Intercept(f(g(h())))`.
func (c *MailboxHiddenMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.MailboxHiddenMessage = append(c.inters.MailboxHiddenMessage, interceptors...)
}

// Create returns a builder for creating a MailboxHiddenMessage entity.
func (c *MailboxHiddenMessageClient) Create() *MailboxHiddenMessageCreate {
	mutation := newMailboxHiddenMessageMutation(c.config, OpCreate)
	return &MailboxHiddenMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MailboxHiddenMessage entities.
func (c *MailboxHiddenMessageClient) CreateBulk(builders ...*MailboxHiddenMessageCreate) *MailboxHiddenMessageCreateBulk {
	return &MailboxHiddenMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MailboxHiddenMessageClient) MapCreateBulk(slice any, setFunc func(*MailboxHiddenMessageCreate, int)) *MailboxHiddenMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MailboxHiddenMessageCreateBulk{err: fmt.Errorf("calling to MailboxHiddenMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MailboxHiddenMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MailboxHiddenMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MailboxHiddenMessage.
func (c *MailboxHiddenMessageClient) Update() *MailboxHiddenMessageUpdate {
	mutation := newMailboxHiddenMessageMutation(c.config, OpUpdate)
	return &MailboxHiddenMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MailboxHiddenMessageClient) UpdateOne(_m *MailboxHiddenMessage) *MailboxHiddenMessageUpdateOne {
	mutation := newMailboxHiddenMessageMutation(c.config, OpUpdateOne, withMailboxHiddenMessage(_m))
	return &MailboxHiddenMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MailboxHiddenMessageClient) UpdateOneID(id int) *MailboxHiddenMessageUpdateOne {
	mutation := newMailboxHiddenMessageMutation(c.config, OpUpdateOne, withMailboxHiddenMessageID(id))
	return &MailboxHiddenMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MailboxHiddenMessage.
func (c *MailboxHiddenMessageClient) Delete() *MailboxHiddenMessageDelete {
	mutation := newMailboxHiddenMessageMutation(c.config, OpDelete)
	return &MailboxHiddenMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MailboxHiddenMessageClient) DeleteOne(_m *MailboxHiddenMessage) *MailboxHiddenMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MailboxHiddenMessageClient) DeleteOneID(id int) *MailboxHiddenMessageDeleteOne {
	builder := c.Delete().Where(mailboxhiddenmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MailboxHiddenMessageDeleteOne{builder}
}

// Query returns a query builder for MailboxHiddenMessage.
func (c *MailboxHiddenMessageClient) Query() *MailboxHiddenMessageQuery {
	return &MailboxHiddenMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMailboxHiddenMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a MailboxHiddenMessage entity by its id.
func (c *MailboxHiddenMessageClient) Get(ctx context.Context, id int) (*MailboxHiddenMessage, error) {
	return c.Query().Where(mailboxhiddenmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MailboxHiddenMessageClient) GetX(ctx context.Context, id int) *MailboxHiddenMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MailboxHiddenMessageClient) Hooks() []Hook {
	return c.hooks.MailboxHiddenMessage
}

// Interceptors returns the client interceptors.
func (c *MailboxHiddenMessageClient) Interceptors() []Interceptor {
	return c.inters.MailboxHiddenMessage
}

func (c *MailboxHiddenMessageClient) mutate(ctx context.Context, m *MailboxHiddenMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MailboxHiddenMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MailboxHiddenMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MailboxHiddenMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MailboxHiddenMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MailboxHiddenMessage mutation op: %q", m.Op())
	}
}

// MailboxMessageClient is a client for the MailboxMessage schema.
type MailboxMessageClient struct {
	config
}

// NewMailboxMessageClient returns a client for the MailboxMessage from the given config.
func NewMailboxMessageClient(c config) *MailboxMessageClient {
	return &MailboxMessageClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mailboxmessage.Hooks(f(g(h())))`.
func (c *MailboxMessageClient) Use(hooks ...Hook) {
	c.hooks.MailboxMessage = append(c.hooks.MailboxMessage, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mailboxmessage.Intercept(f(g(h())))`.
func (c *MailboxMessageClient) Intercept(interceptors ...Interceptor) {
	c.inters.MailboxMessage = append(c.inters.MailboxMessage, interceptors...)
}

// Create returns a builder for creating a MailboxMessage entity.
func (c *MailboxMessageClient) Create() *MailboxMessageCreate {
	mutation := newMailboxMessageMutation(c.config, OpCreate)
	return &MailboxMessageCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MailboxMessage entities.
func (c *MailboxMessageClient) CreateBulk(builders ...*MailboxMessageCreate) *MailboxMessageCreateBulk {
	return &MailboxMessageCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MailboxMessageClient) MapCreateBulk(slice any, setFunc func(*MailboxMessageCreate, int)) *MailboxMessageCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MailboxMessageCreateBulk{err: fmt.Errorf("calling to MailboxMessageClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MailboxMessageCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MailboxMessageCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MailboxMessage.
func (c *MailboxMessageClient) Update() *MailboxMessageUpdate {
	mutation := newMailboxMessageMutation(c.config, OpUpdate)
	return &MailboxMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MailboxMessageClient) UpdateOne(_m *MailboxMessage) *MailboxMessageUpdateOne {
	mutation := newMailboxMessageMutation(c.config, OpUpdateOne, withMailboxMessage(_m))
	return &MailboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MailboxMessageClient) UpdateOneID(id int) *MailboxMessageUpdateOne {
	mutation := newMailboxMessageMutation(c.config, OpUpdateOne, withMailboxMessageID(id))
	return &MailboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MailboxMessage.
func (c *MailboxMessageClient) Delete() *MailboxMessageDelete {
	mutation := newMailboxMessageMutation(c.config, OpDelete)
	return &MailboxMessageDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MailboxMessageClient) DeleteOne(_m *MailboxMessage) *MailboxMessageDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MailboxMessageClient) DeleteOneID(id int) *MailboxMessageDeleteOne {
	builder := c.Delete().Where(mailboxmessage.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MailboxMessageDeleteOne{builder}
}

// Query returns a query builder for MailboxMessage.
func (c *MailboxMessageClient) Query() *MailboxMessageQuery {
	return &MailboxMessageQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMailboxMessage},
		inters: c.Interceptors(),
	}
}

// Get returns a MailboxMessage entity by its id.
func (c *MailboxMessageClient) Get(ctx context.Context, id int) (*MailboxMessage, error) {
	return c.Query().Where(mailboxmessage.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MailboxMessageClient) GetX(ctx context.Context, id int) *MailboxMessage {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MailboxMessageClient) Hooks() []Hook {
	return c.hooks.MailboxMessage
}

// Interceptors returns the client interceptors.
func (c *MailboxMessageClient) Interceptors() []Interceptor {
	return c.inters.MailboxMessage
}

func (c *MailboxMessageClient) mutate(ctx context.Context, m *MailboxMessageMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MailboxMessageCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MailboxMessageUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MailboxMessageUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MailboxMessageDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MailboxMessage mutation op: %q", m.Op())
	}
}

// MailboxSyncStateClient is a client for the MailboxSyncState schema.
type MailboxSyncStateClient struct {
	config
}

// NewMailboxSyncStateClient returns a client for the MailboxSyncState from the given config.
func NewMailboxSyncStateClient(c config) *MailboxSyncStateClient {
	return &MailboxSyncStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `mailboxsyncstate.Hooks(f(g(h())))`.
func (c *MailboxSyncStateClient) Use(hooks ...Hook) {
	c.hooks.MailboxSyncState = append(c.hooks.MailboxSyncState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `mailboxsyncstate.Intercept(f(g(h())))`.
func (c *MailboxSyncStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.MailboxSyncState = append(c.inters.MailboxSyncState, interceptors...)
}

// Create returns a builder for creating a MailboxSyncState entity.
func (c *MailboxSyncStateClient) Create() *MailboxSyncStateCreate {
	mutation := newMailboxSyncStateMutation(c.config, OpCreate)
	return &MailboxSyncStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MailboxSyncState entities.
func (c *MailboxSyncStateClient) CreateBulk(builders ...*MailboxSyncStateCreate) *MailboxSyncStateCreateBulk {
	return &MailboxSyncStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MailboxSyncStateClient) MapCreateBulk(slice any, setFunc func(*MailboxSyncStateCreate, int)) *MailboxSyncStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MailboxSyncStateCreateBulk{err: fmt.Errorf("calling to MailboxSyncStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MailboxSyncStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MailboxSyncStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MailboxSyncState.
func (c *MailboxSyncStateClient) Update() *MailboxSyncStateUpdate {
	mutation := newMailboxSyncStateMutation(c.config, OpUpdate)
	return &MailboxSyncStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MailboxSyncStateClient) UpdateOne(_m *MailboxSyncState) *MailboxSyncStateUpdateOne {
	mutation := newMailboxSyncStateMutation(c.config, OpUpdateOne, withMailboxSyncState(_m))
	return &MailboxSyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MailboxSyncStateClient) UpdateOneID(id int) *MailboxSyncStateUpdateOne {
	mutation := newMailboxSyncStateMutation(c.config, OpUpdateOne, withMailboxSyncStateID(id))
	return &MailboxSyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MailboxSyncState.
func (c *MailboxSyncStateClient) Delete() *MailboxSyncStateDelete {
	mutation := newMailboxSyncStateMutation(c.config, OpDelete)
	return &MailboxSyncStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MailboxSyncStateClient) DeleteOne(_m *MailboxSyncState) *MailboxSyncStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MailboxSyncStateClient) DeleteOneID(id int) *MailboxSyncStateDeleteOne {
	builder := c.Delete().Where(mailboxsyncstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MailboxSyncStateDeleteOne{builder}
}

// Query returns a query builder for MailboxSyncState.
func (c *MailboxSyncStateClient) Query() *MailboxSyncStateQuery {
	return &MailboxSyncStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMailboxSyncState},
		inters: c.Interceptors(),
	}
}

// Get returns a MailboxSyncState entity by its id.
func (c *MailboxSyncStateClient) Get(ctx context.Context, id int) (*MailboxSyncState, error) {
	return c.Query().Where(mailboxsyncstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MailboxSyncStateClient) GetX(ctx context.Context, id int) *MailboxSyncState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MailboxSyncStateClient) Hooks() []Hook {
	return c.hooks.MailboxSyncState
}

// Interceptors returns the client interceptors.
func (c *MailboxSyncStateClient) Interceptors() []Interceptor {
	return c.inters.MailboxSyncState
}

func (c *MailboxSyncStateClient) mutate(ctx context.Context, m *MailboxSyncStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MailboxSyncStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MailboxSyncStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MailboxSyncStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MailboxSyncStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MailboxSyncState mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		MailboxHiddenMessage, MailboxMessage, MailboxSyncState []ent.Hook
	}
	inters struct {
		MailboxHiddenMessage, MailboxMessage, MailboxSyncState []ent.Interceptor
	}
)
