// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailaliasappstate"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// MailAliasAppStateUpdate is the builder for updating MailAliasAppState entities.
type MailAliasAppStateUpdate struct {
	config
	hooks    []Hook
	mutation *MailAliasAppStateMutation
}

// Where appends a list predicates to the MailAliasAppStateUpdate builder.
func (_u *MailAliasAppStateUpdate) Where(ps ...predicate.MailAliasAppState) *MailAliasAppStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MailAliasAppStateUpdate) SetAccountID(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableAccountID(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *MailAliasAppStateUpdate) SetAlias(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableAlias(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetAppKey sets the "app_key" field.
func (_u *MailAliasAppStateUpdate) SetAppKey(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetAppKey(v)
	return _u
}

// SetNillableAppKey sets the "app_key" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableAppKey(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetAppKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailAliasAppStateUpdate) SetStatus(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableStatus(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *MailAliasAppStateUpdate) SetDetectedAt(v time.Time) *MailAliasAppStateUpdate {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableDetectedAt(v *time.Time) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// ClearDetectedAt clears the value of the "detected_at" field.
func (_u *MailAliasAppStateUpdate) ClearDetectedAt() *MailAliasAppStateUpdate {
	_u.mutation.ClearDetectedAt()
	return _u
}

// SetDetectedUID sets the "detected_uid" field.
func (_u *MailAliasAppStateUpdate) SetDetectedUID(v uint64) *MailAliasAppStateUpdate {
	_u.mutation.ResetDetectedUID()
	_u.mutation.SetDetectedUID(v)
	return _u
}

// SetNillableDetectedUID sets the "detected_uid" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableDetectedUID(v *uint64) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetDetectedUID(*v)
	}
	return _u
}

// AddDetectedUID adds value to the "detected_uid" field.
func (_u *MailAliasAppStateUpdate) AddDetectedUID(v int64) *MailAliasAppStateUpdate {
	_u.mutation.AddDetectedUID(v)
	return _u
}

// SetDetectedSubject sets the "detected_subject" field.
func (_u *MailAliasAppStateUpdate) SetDetectedSubject(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetDetectedSubject(v)
	return _u
}

// SetNillableDetectedSubject sets the "detected_subject" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableDetectedSubject(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetDetectedSubject(*v)
	}
	return _u
}

// SetDetectedSender sets the "detected_sender" field.
func (_u *MailAliasAppStateUpdate) SetDetectedSender(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetDetectedSender(v)
	return _u
}

// SetNillableDetectedSender sets the "detected_sender" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableDetectedSender(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetDetectedSender(*v)
	}
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *MailAliasAppStateUpdate) SetConfirmedAt(v time.Time) *MailAliasAppStateUpdate {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableConfirmedAt(v *time.Time) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *MailAliasAppStateUpdate) ClearConfirmedAt() *MailAliasAppStateUpdate {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetConfirmedUID sets the "confirmed_uid" field.
func (_u *MailAliasAppStateUpdate) SetConfirmedUID(v uint64) *MailAliasAppStateUpdate {
	_u.mutation.ResetConfirmedUID()
	_u.mutation.SetConfirmedUID(v)
	return _u
}

// SetNillableConfirmedUID sets the "confirmed_uid" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableConfirmedUID(v *uint64) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetConfirmedUID(*v)
	}
	return _u
}

// AddConfirmedUID adds value to the "confirmed_uid" field.
func (_u *MailAliasAppStateUpdate) AddConfirmedUID(v int64) *MailAliasAppStateUpdate {
	_u.mutation.AddConfirmedUID(v)
	return _u
}

// SetConfirmedSubject sets the "confirmed_subject" field.
func (_u *MailAliasAppStateUpdate) SetConfirmedSubject(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetConfirmedSubject(v)
	return _u
}

// SetNillableConfirmedSubject sets the "confirmed_subject" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableConfirmedSubject(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetConfirmedSubject(*v)
	}
	return _u
}

// SetConfirmedSender sets the "confirmed_sender" field.
func (_u *MailAliasAppStateUpdate) SetConfirmedSender(v string) *MailAliasAppStateUpdate {
	_u.mutation.SetConfirmedSender(v)
	return _u
}

// SetNillableConfirmedSender sets the "confirmed_sender" field if the given value is not nil.
func (_u *MailAliasAppStateUpdate) SetNillableConfirmedSender(v *string) *MailAliasAppStateUpdate {
	if v != nil {
		_u.SetConfirmedSender(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailAliasAppStateUpdate) SetUpdatedAt(v time.Time) *MailAliasAppStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MailAliasAppStateMutation object of the builder.
func (_u *MailAliasAppStateUpdate) Mutation() *MailAliasAppStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailAliasAppStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailAliasAppStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailAliasAppStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailAliasAppStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailAliasAppStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailaliasappstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailAliasAppStateUpdate) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mailaliasappstate.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Alias(); ok {
		if err := mailaliasappstate.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppKey(); ok {
		if err := mailaliasappstate.AppKeyValidator(v); err != nil {
			return &ValidationError{Name: "app_key", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.app_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mailaliasappstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectedSubject(); ok {
		if err := mailaliasappstate.DetectedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "detected_subject", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.detected_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectedSender(); ok {
		if err := mailaliasappstate.DetectedSenderValidator(v); err != nil {
			return &ValidationError{Name: "detected_sender", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.detected_sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedSubject(); ok {
		if err := mailaliasappstate.ConfirmedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_subject", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.confirmed_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedSender(); ok {
		if err := mailaliasappstate.ConfirmedSenderValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_sender", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.confirmed_sender": %w`, err)}
		}
	}
	return nil
}

func (_u *MailAliasAppStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailaliasappstate.Table, mailaliasappstate.Columns, sqlgraph.NewFieldSpec(mailaliasappstate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mailaliasappstate.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(mailaliasappstate.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppKey(); ok {
		_spec.SetField(mailaliasappstate.FieldAppKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mailaliasappstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedAt, field.TypeTime, value)
	}
	if _u.mutation.DetectedAtCleared() {
		_spec.ClearField(mailaliasappstate.FieldDetectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DetectedUID(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDetectedUID(); ok {
		_spec.AddField(mailaliasappstate.FieldDetectedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DetectedSubject(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectedSender(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(mailaliasappstate.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfirmedUID(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedConfirmedUID(); ok {
		_spec.AddField(mailaliasappstate.FieldConfirmedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ConfirmedSubject(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedSender(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailaliasappstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailAliasAppStateUpdateOne is the builder for updating a single MailAliasAppState entity.
type MailAliasAppStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailAliasAppStateMutation
}

// SetAccountID sets the "account_id" field.
func (_u *MailAliasAppStateUpdateOne) SetAccountID(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableAccountID(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *MailAliasAppStateUpdateOne) SetAlias(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableAlias(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// SetAppKey sets the "app_key" field.
func (_u *MailAliasAppStateUpdateOne) SetAppKey(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetAppKey(v)
	return _u
}

// SetNillableAppKey sets the "app_key" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableAppKey(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetAppKey(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MailAliasAppStateUpdateOne) SetStatus(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableStatus(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *MailAliasAppStateUpdateOne) SetDetectedAt(v time.Time) *MailAliasAppStateUpdateOne {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableDetectedAt(v *time.Time) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// ClearDetectedAt clears the value of the "detected_at" field.
func (_u *MailAliasAppStateUpdateOne) ClearDetectedAt() *MailAliasAppStateUpdateOne {
	_u.mutation.ClearDetectedAt()
	return _u
}

// SetDetectedUID sets the "detected_uid" field.
func (_u *MailAliasAppStateUpdateOne) SetDetectedUID(v uint64) *MailAliasAppStateUpdateOne {
	_u.mutation.ResetDetectedUID()
	_u.mutation.SetDetectedUID(v)
	return _u
}

// SetNillableDetectedUID sets the "detected_uid" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableDetectedUID(v *uint64) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetDetectedUID(*v)
	}
	return _u
}

// AddDetectedUID adds value to the "detected_uid" field.
func (_u *MailAliasAppStateUpdateOne) AddDetectedUID(v int64) *MailAliasAppStateUpdateOne {
	_u.mutation.AddDetectedUID(v)
	return _u
}

// SetDetectedSubject sets the "detected_subject" field.
func (_u *MailAliasAppStateUpdateOne) SetDetectedSubject(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetDetectedSubject(v)
	return _u
}

// SetNillableDetectedSubject sets the "detected_subject" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableDetectedSubject(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetDetectedSubject(*v)
	}
	return _u
}

// SetDetectedSender sets the "detected_sender" field.
func (_u *MailAliasAppStateUpdateOne) SetDetectedSender(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetDetectedSender(v)
	return _u
}

// SetNillableDetectedSender sets the "detected_sender" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableDetectedSender(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetDetectedSender(*v)
	}
	return _u
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_u *MailAliasAppStateUpdateOne) SetConfirmedAt(v time.Time) *MailAliasAppStateUpdateOne {
	_u.mutation.SetConfirmedAt(v)
	return _u
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableConfirmedAt(v *time.Time) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetConfirmedAt(*v)
	}
	return _u
}

// ClearConfirmedAt clears the value of the "confirmed_at" field.
func (_u *MailAliasAppStateUpdateOne) ClearConfirmedAt() *MailAliasAppStateUpdateOne {
	_u.mutation.ClearConfirmedAt()
	return _u
}

// SetConfirmedUID sets the "confirmed_uid" field.
func (_u *MailAliasAppStateUpdateOne) SetConfirmedUID(v uint64) *MailAliasAppStateUpdateOne {
	_u.mutation.ResetConfirmedUID()
	_u.mutation.SetConfirmedUID(v)
	return _u
}

// SetNillableConfirmedUID sets the "confirmed_uid" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableConfirmedUID(v *uint64) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetConfirmedUID(*v)
	}
	return _u
}

// AddConfirmedUID adds value to the "confirmed_uid" field.
func (_u *MailAliasAppStateUpdateOne) AddConfirmedUID(v int64) *MailAliasAppStateUpdateOne {
	_u.mutation.AddConfirmedUID(v)
	return _u
}

// SetConfirmedSubject sets the "confirmed_subject" field.
func (_u *MailAliasAppStateUpdateOne) SetConfirmedSubject(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetConfirmedSubject(v)
	return _u
}

// SetNillableConfirmedSubject sets the "confirmed_subject" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableConfirmedSubject(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetConfirmedSubject(*v)
	}
	return _u
}

// SetConfirmedSender sets the "confirmed_sender" field.
func (_u *MailAliasAppStateUpdateOne) SetConfirmedSender(v string) *MailAliasAppStateUpdateOne {
	_u.mutation.SetConfirmedSender(v)
	return _u
}

// SetNillableConfirmedSender sets the "confirmed_sender" field if the given value is not nil.
func (_u *MailAliasAppStateUpdateOne) SetNillableConfirmedSender(v *string) *MailAliasAppStateUpdateOne {
	if v != nil {
		_u.SetConfirmedSender(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MailAliasAppStateUpdateOne) SetUpdatedAt(v time.Time) *MailAliasAppStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MailAliasAppStateMutation object of the builder.
func (_u *MailAliasAppStateUpdateOne) Mutation() *MailAliasAppStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the MailAliasAppStateUpdate builder.
func (_u *MailAliasAppStateUpdateOne) Where(ps ...predicate.MailAliasAppState) *MailAliasAppStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailAliasAppStateUpdateOne) Select(field string, fields ...string) *MailAliasAppStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MailAliasAppState entity.
func (_u *MailAliasAppStateUpdateOne) Save(ctx context.Context) (*MailAliasAppState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailAliasAppStateUpdateOne) SaveX(ctx context.Context) *MailAliasAppState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailAliasAppStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailAliasAppStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MailAliasAppStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := mailaliasappstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailAliasAppStateUpdateOne) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mailaliasappstate.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Alias(); ok {
		if err := mailaliasappstate.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.alias": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppKey(); ok {
		if err := mailaliasappstate.AppKeyValidator(v); err != nil {
			return &ValidationError{Name: "app_key", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.app_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := mailaliasappstate.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectedSubject(); ok {
		if err := mailaliasappstate.DetectedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "detected_subject", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.detected_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectedSender(); ok {
		if err := mailaliasappstate.DetectedSenderValidator(v); err != nil {
			return &ValidationError{Name: "detected_sender", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.detected_sender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedSubject(); ok {
		if err := mailaliasappstate.ConfirmedSubjectValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_subject", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.confirmed_subject": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfirmedSender(); ok {
		if err := mailaliasappstate.ConfirmedSenderValidator(v); err != nil {
			return &ValidationError{Name: "confirmed_sender", err: fmt.Errorf(`ent: validator failed for field "MailAliasAppState.confirmed_sender": %w`, err)}
		}
	}
	return nil
}

func (_u *MailAliasAppStateUpdateOne) sqlSave(ctx context.Context) (_node *MailAliasAppState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailaliasappstate.Table, mailaliasappstate.Columns, sqlgraph.NewFieldSpec(mailaliasappstate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MailAliasAppState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailaliasappstate.FieldID)
		for _, f := range fields {
			if !mailaliasappstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mailaliasappstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mailaliasappstate.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(mailaliasappstate.FieldAlias, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppKey(); ok {
		_spec.SetField(mailaliasappstate.FieldAppKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(mailaliasappstate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedAt, field.TypeTime, value)
	}
	if _u.mutation.DetectedAtCleared() {
		_spec.ClearField(mailaliasappstate.FieldDetectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DetectedUID(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDetectedUID(); ok {
		_spec.AddField(mailaliasappstate.FieldDetectedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DetectedSubject(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectedSender(); ok {
		_spec.SetField(mailaliasappstate.FieldDetectedSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedAt, field.TypeTime, value)
	}
	if _u.mutation.ConfirmedAtCleared() {
		_spec.ClearField(mailaliasappstate.FieldConfirmedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfirmedUID(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedConfirmedUID(); ok {
		_spec.AddField(mailaliasappstate.FieldConfirmedUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ConfirmedSubject(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfirmedSender(); ok {
		_spec.SetField(mailaliasappstate.FieldConfirmedSender, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(mailaliasappstate.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &MailAliasAppState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailaliasappstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
