// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxsyncstate"
)

// MailboxSyncState is the model entity for the MailboxSyncState schema.
type MailboxSyncState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Status holds the value of the "status" field.
	Status map[string]interface{} `json:"status,omitempty"`
	// HighestUID holds the value of the "highest_uid" field.
	HighestUID uint64 `json:"highest_uid,omitempty"`
	// AllowedAliases holds the value of the "allowed_aliases" field.
	AllowedAliases []string `json:"allowed_aliases,omitempty"`
	selectValues   sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MailboxSyncState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mailboxsyncstate.FieldStatus, mailboxsyncstate.FieldAllowedAliases:
			values[i] = new([]byte)
		case mailboxsyncstate.FieldID, mailboxsyncstate.FieldHighestUID:
			values[i] = new(sql.NullInt64)
		case mailboxsyncstate.FieldAccountID, mailboxsyncstate.FieldKey:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MailboxSyncState fields.
func (_m *MailboxSyncState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mailboxsyncstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mailboxsyncstate.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case mailboxsyncstate.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case mailboxsyncstate.FieldStatus:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Status); err != nil {
					return fmt.Errorf("unmarshal field status: %w", err)
				}
			}
		case mailboxsyncstate.FieldHighestUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field highest_uid", values[i])
			} else if value.Valid {
				_m.HighestUID = uint64(value.Int64)
			}
		case mailboxsyncstate.FieldAllowedAliases:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_aliases", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AllowedAliases); err != nil {
					return fmt.Errorf("unmarshal field allowed_aliases: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MailboxSyncState.
// This includes values selected through modifiers, order, etc.
func (_m *MailboxSyncState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MailboxSyncState.
// Note that you need to call MailboxSyncState.Unwrap() before calling this method if this MailboxSyncState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MailboxSyncState) Update() *MailboxSyncStateUpdateOne {
	return NewMailboxSyncStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MailboxSyncState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MailboxSyncState) Unwrap() *MailboxSyncState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MailboxSyncState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MailboxSyncState) String() string {
	var builder strings.Builder
	builder.WriteString("MailboxSyncState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("highest_uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.HighestUID))
	builder.WriteString(", ")
	builder.WriteString("allowed_aliases=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowedAliases))
	builder.WriteByte(')')
	return builder.String()
}

// MailboxSyncStates is a parsable slice of MailboxSyncState.
type MailboxSyncStates []*MailboxSyncState
