// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
)

// MailboxMessageCreate is the builder for creating a MailboxMessage entity.
type MailboxMessageCreate struct {
	config
	mutation *MailboxMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAccountID sets the "account_id" field.
func (_c *MailboxMessageCreate) SetAccountID(v string) *MailboxMessageCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableAccountID(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetGeneration sets the "generation" field.
func (_c *MailboxMessageCreate) SetGeneration(v string) *MailboxMessageCreate {
	_c.mutation.SetGeneration(v)
	return _c
}

// SetUID sets the "uid" field.
func (_c *MailboxMessageCreate) SetUID(v uint64) *MailboxMessageCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetAliases sets the "aliases" field.
func (_c *MailboxMessageCreate) SetAliases(v []string) *MailboxMessageCreate {
	_c.mutation.SetAliases(v)
	return _c
}

// SetFromAddress sets the "from_address" field.
func (_c *MailboxMessageCreate) SetFromAddress(v string) *MailboxMessageCreate {
	_c.mutation.SetFromAddress(v)
	return _c
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableFromAddress(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetFromAddress(*v)
	}
	return _c
}

// SetSubject sets the "subject" field.
func (_c *MailboxMessageCreate) SetSubject(v string) *MailboxMessageCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableSubject(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetSubject(*v)
	}
	return _c
}

// SetMessageDate sets the "message_date" field.
func (_c *MailboxMessageCreate) SetMessageDate(v float64) *MailboxMessageCreate {
	_c.mutation.SetMessageDate(v)
	return _c
}

// SetText sets the "text" field.
func (_c *MailboxMessageCreate) SetText(v string) *MailboxMessageCreate {
	_c.mutation.SetText(v)
	return _c
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableText(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetText(*v)
	}
	return _c
}

// SetSafeHTML sets the "safe_html" field.
func (_c *MailboxMessageCreate) SetSafeHTML(v string) *MailboxMessageCreate {
	_c.mutation.SetSafeHTML(v)
	return _c
}

// SetNillableSafeHTML sets the "safe_html" field if the given value is not nil.
func (_c *MailboxMessageCreate) SetNillableSafeHTML(v *string) *MailboxMessageCreate {
	if v != nil {
		_c.SetSafeHTML(*v)
	}
	return _c
}

// SetCodes sets the "codes" field.
func (_c *MailboxMessageCreate) SetCodes(v []string) *MailboxMessageCreate {
	_c.mutation.SetCodes(v)
	return _c
}

// SetPartnerCodes sets the "partner_codes" field.
func (_c *MailboxMessageCreate) SetPartnerCodes(v []string) *MailboxMessageCreate {
	_c.mutation.SetPartnerCodes(v)
	return _c
}

// Mutation returns the MailboxMessageMutation object of the builder.
func (_c *MailboxMessageCreate) Mutation() *MailboxMessageMutation {
	return _c.mutation
}

// Save creates the MailboxMessage in the database.
func (_c *MailboxMessageCreate) Save(ctx context.Context) (*MailboxMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MailboxMessageCreate) SaveX(ctx context.Context) *MailboxMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MailboxMessageCreate) defaults() {
	if _, ok := _c.mutation.AccountID(); !ok {
		v := mailboxmessage.DefaultAccountID
		_c.mutation.SetAccountID(v)
	}
	if _, ok := _c.mutation.Aliases(); !ok {
		v := mailboxmessage.DefaultAliases
		_c.mutation.SetAliases(v)
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		v := mailboxmessage.DefaultFromAddress
		_c.mutation.SetFromAddress(v)
	}
	if _, ok := _c.mutation.Subject(); !ok {
		v := mailboxmessage.DefaultSubject
		_c.mutation.SetSubject(v)
	}
	if _, ok := _c.mutation.Text(); !ok {
		v := mailboxmessage.DefaultText
		_c.mutation.SetText(v)
	}
	if _, ok := _c.mutation.SafeHTML(); !ok {
		v := mailboxmessage.DefaultSafeHTML
		_c.mutation.SetSafeHTML(v)
	}
	if _, ok := _c.mutation.Codes(); !ok {
		v := mailboxmessage.DefaultCodes
		_c.mutation.SetCodes(v)
	}
	if _, ok := _c.mutation.PartnerCodes(); !ok {
		v := mailboxmessage.DefaultPartnerCodes
		_c.mutation.SetPartnerCodes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MailboxMessageCreate) check() error {
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "MailboxMessage.account_id"`)}
	}
	if v, ok := _c.mutation.AccountID(); ok {
		if err := mailboxmessage.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.account_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Generation(); !ok {
		return &ValidationError{Name: "generation", err: errors.New(`ent: missing required field "MailboxMessage.generation"`)}
	}
	if v, ok := _c.mutation.Generation(); ok {
		if err := mailboxmessage.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.generation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "MailboxMessage.uid"`)}
	}
	if _, ok := _c.mutation.Aliases(); !ok {
		return &ValidationError{Name: "aliases", err: errors.New(`ent: missing required field "MailboxMessage.aliases"`)}
	}
	if _, ok := _c.mutation.FromAddress(); !ok {
		return &ValidationError{Name: "from_address", err: errors.New(`ent: missing required field "MailboxMessage.from_address"`)}
	}
	if v, ok := _c.mutation.FromAddress(); ok {
		if err := mailboxmessage.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.from_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "MailboxMessage.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := mailboxmessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageDate(); !ok {
		return &ValidationError{Name: "message_date", err: errors.New(`ent: missing required field "MailboxMessage.message_date"`)}
	}
	if _, ok := _c.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "MailboxMessage.text"`)}
	}
	if _, ok := _c.mutation.SafeHTML(); !ok {
		return &ValidationError{Name: "safe_html", err: errors.New(`ent: missing required field "MailboxMessage.safe_html"`)}
	}
	if _, ok := _c.mutation.Codes(); !ok {
		return &ValidationError{Name: "codes", err: errors.New(`ent: missing required field "MailboxMessage.codes"`)}
	}
	if _, ok := _c.mutation.PartnerCodes(); !ok {
		return &ValidationError{Name: "partner_codes", err: errors.New(`ent: missing required field "MailboxMessage.partner_codes"`)}
	}
	return nil
}

func (_c *MailboxMessageCreate) sqlSave(ctx context.Context) (*MailboxMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MailboxMessageCreate) createSpec() (*MailboxMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &MailboxMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mailboxmessage.Table, sqlgraph.NewFieldSpec(mailboxmessage.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(mailboxmessage.FieldAccountID, field.TypeString, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.Generation(); ok {
		_spec.SetField(mailboxmessage.FieldGeneration, field.TypeString, value)
		_node.Generation = value
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(mailboxmessage.FieldUID, field.TypeUint64, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Aliases(); ok {
		_spec.SetField(mailboxmessage.FieldAliases, field.TypeJSON, value)
		_node.Aliases = value
	}
	if value, ok := _c.mutation.FromAddress(); ok {
		_spec.SetField(mailboxmessage.FieldFromAddress, field.TypeString, value)
		_node.FromAddress = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(mailboxmessage.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.MessageDate(); ok {
		_spec.SetField(mailboxmessage.FieldMessageDate, field.TypeFloat64, value)
		_node.MessageDate = value
	}
	if value, ok := _c.mutation.Text(); ok {
		_spec.SetField(mailboxmessage.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := _c.mutation.SafeHTML(); ok {
		_spec.SetField(mailboxmessage.FieldSafeHTML, field.TypeString, value)
		_node.SafeHTML = value
	}
	if value, ok := _c.mutation.Codes(); ok {
		_spec.SetField(mailboxmessage.FieldCodes, field.TypeJSON, value)
		_node.Codes = value
	}
	if value, ok := _c.mutation.PartnerCodes(); ok {
		_spec.SetField(mailboxmessage.FieldPartnerCodes, field.TypeJSON, value)
		_node.PartnerCodes = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailboxMessage.Create().
//		SetAccountID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MailboxMessageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *MailboxMessageCreate) OnConflict(opts ...sql.ConflictOption) *MailboxMessageUpsertOne {
	_c.conflict = opts
	return &MailboxMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MailboxMessageCreate) OnConflictColumns(columns ...string) *MailboxMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MailboxMessageUpsertOne{
		create: _c,
	}
}

type (
	// MailboxMessageUpsertOne is the builder for "upsert"-ing
	//  one MailboxMessage node.
	MailboxMessageUpsertOne struct {
		create *MailboxMessageCreate
	}

	// MailboxMessageUpsert is the "OnConflict" setter.
	MailboxMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *MailboxMessageUpsert) SetAccountID(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateAccountID() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldAccountID)
	return u
}

// SetGeneration sets the "generation" field.
func (u *MailboxMessageUpsert) SetGeneration(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldGeneration, v)
	return u
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateGeneration() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldGeneration)
	return u
}

// SetUID sets the "uid" field.
func (u *MailboxMessageUpsert) SetUID(v uint64) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldUID, v)
	return u
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateUID() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldUID)
	return u
}

// AddUID adds v to the "uid" field.
func (u *MailboxMessageUpsert) AddUID(v uint64) *MailboxMessageUpsert {
	u.Add(mailboxmessage.FieldUID, v)
	return u
}

// SetAliases sets the "aliases" field.
func (u *MailboxMessageUpsert) SetAliases(v []string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldAliases, v)
	return u
}

// UpdateAliases sets the "aliases" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateAliases() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldAliases)
	return u
}

// SetFromAddress sets the "from_address" field.
func (u *MailboxMessageUpsert) SetFromAddress(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldFromAddress, v)
	return u
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateFromAddress() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldFromAddress)
	return u
}

// SetSubject sets the "subject" field.
func (u *MailboxMessageUpsert) SetSubject(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldSubject, v)
	return u
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateSubject() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldSubject)
	return u
}

// SetMessageDate sets the "message_date" field.
func (u *MailboxMessageUpsert) SetMessageDate(v float64) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldMessageDate, v)
	return u
}

// UpdateMessageDate sets the "message_date" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateMessageDate() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldMessageDate)
	return u
}

// AddMessageDate adds v to the "message_date" field.
func (u *MailboxMessageUpsert) AddMessageDate(v float64) *MailboxMessageUpsert {
	u.Add(mailboxmessage.FieldMessageDate, v)
	return u
}

// SetText sets the "text" field.
func (u *MailboxMessageUpsert) SetText(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldText, v)
	return u
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateText() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldText)
	return u
}

// SetSafeHTML sets the "safe_html" field.
func (u *MailboxMessageUpsert) SetSafeHTML(v string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldSafeHTML, v)
	return u
}

// UpdateSafeHTML sets the "safe_html" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateSafeHTML() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldSafeHTML)
	return u
}

// SetCodes sets the "codes" field.
func (u *MailboxMessageUpsert) SetCodes(v []string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldCodes, v)
	return u
}

// UpdateCodes sets the "codes" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdateCodes() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldCodes)
	return u
}

// SetPartnerCodes sets the "partner_codes" field.
func (u *MailboxMessageUpsert) SetPartnerCodes(v []string) *MailboxMessageUpsert {
	u.Set(mailboxmessage.FieldPartnerCodes, v)
	return u
}

// UpdatePartnerCodes sets the "partner_codes" field to the value that was provided on create.
func (u *MailboxMessageUpsert) UpdatePartnerCodes() *MailboxMessageUpsert {
	u.SetExcluded(mailboxmessage.FieldPartnerCodes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MailboxMessageUpsertOne) UpdateNewValues() *MailboxMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MailboxMessageUpsertOne) Ignore() *MailboxMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailboxMessageUpsertOne) DoNothing() *MailboxMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailboxMessageCreate.OnConflict
// documentation for more info.
func (u *MailboxMessageUpsertOne) Update(set func(*MailboxMessageUpsert)) *MailboxMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailboxMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *MailboxMessageUpsertOne) SetAccountID(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateAccountID() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateAccountID()
	})
}

// SetGeneration sets the "generation" field.
func (u *MailboxMessageUpsertOne) SetGeneration(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateGeneration() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateGeneration()
	})
}

// SetUID sets the "uid" field.
func (u *MailboxMessageUpsertOne) SetUID(v uint64) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *MailboxMessageUpsertOne) AddUID(v uint64) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateUID() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateUID()
	})
}

// SetAliases sets the "aliases" field.
func (u *MailboxMessageUpsertOne) SetAliases(v []string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetAliases(v)
	})
}

// UpdateAliases sets the "aliases" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateAliases() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateAliases()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *MailboxMessageUpsertOne) SetFromAddress(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateFromAddress() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateFromAddress()
	})
}

// SetSubject sets the "subject" field.
func (u *MailboxMessageUpsertOne) SetSubject(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateSubject() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetMessageDate sets the "message_date" field.
func (u *MailboxMessageUpsertOne) SetMessageDate(v float64) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetMessageDate(v)
	})
}

// AddMessageDate adds v to the "message_date" field.
func (u *MailboxMessageUpsertOne) AddMessageDate(v float64) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.AddMessageDate(v)
	})
}

// UpdateMessageDate sets the "message_date" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateMessageDate() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateMessageDate()
	})
}

// SetText sets the "text" field.
func (u *MailboxMessageUpsertOne) SetText(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateText() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateText()
	})
}

// SetSafeHTML sets the "safe_html" field.
func (u *MailboxMessageUpsertOne) SetSafeHTML(v string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetSafeHTML(v)
	})
}

// UpdateSafeHTML sets the "safe_html" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateSafeHTML() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateSafeHTML()
	})
}

// SetCodes sets the "codes" field.
func (u *MailboxMessageUpsertOne) SetCodes(v []string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetCodes(v)
	})
}

// UpdateCodes sets the "codes" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdateCodes() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateCodes()
	})
}

// SetPartnerCodes sets the "partner_codes" field.
func (u *MailboxMessageUpsertOne) SetPartnerCodes(v []string) *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetPartnerCodes(v)
	})
}

// UpdatePartnerCodes sets the "partner_codes" field to the value that was provided on create.
func (u *MailboxMessageUpsertOne) UpdatePartnerCodes() *MailboxMessageUpsertOne {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdatePartnerCodes()
	})
}

// Exec executes the query.
func (u *MailboxMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailboxMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailboxMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MailboxMessageUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MailboxMessageUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MailboxMessageCreateBulk is the builder for creating many MailboxMessage entities in bulk.
type MailboxMessageCreateBulk struct {
	config
	err      error
	builders []*MailboxMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the MailboxMessage entities in the database.
func (_c *MailboxMessageCreateBulk) Save(ctx context.Context) ([]*MailboxMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MailboxMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MailboxMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MailboxMessageCreateBulk) SaveX(ctx context.Context) []*MailboxMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MailboxMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MailboxMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MailboxMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MailboxMessageUpsert) {
//			SetAccountID(v+v).
//		}).
//		Exec(ctx)
func (_c *MailboxMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *MailboxMessageUpsertBulk {
	_c.conflict = opts
	return &MailboxMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MailboxMessageCreateBulk) OnConflictColumns(columns ...string) *MailboxMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MailboxMessageUpsertBulk{
		create: _c,
	}
}

// MailboxMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of MailboxMessage nodes.
type MailboxMessageUpsertBulk struct {
	create *MailboxMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MailboxMessageUpsertBulk) UpdateNewValues() *MailboxMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MailboxMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MailboxMessageUpsertBulk) Ignore() *MailboxMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MailboxMessageUpsertBulk) DoNothing() *MailboxMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MailboxMessageCreateBulk.OnConflict
// documentation for more info.
func (u *MailboxMessageUpsertBulk) Update(set func(*MailboxMessageUpsert)) *MailboxMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MailboxMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *MailboxMessageUpsertBulk) SetAccountID(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateAccountID() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateAccountID()
	})
}

// SetGeneration sets the "generation" field.
func (u *MailboxMessageUpsertBulk) SetGeneration(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetGeneration(v)
	})
}

// UpdateGeneration sets the "generation" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateGeneration() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateGeneration()
	})
}

// SetUID sets the "uid" field.
func (u *MailboxMessageUpsertBulk) SetUID(v uint64) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetUID(v)
	})
}

// AddUID adds v to the "uid" field.
func (u *MailboxMessageUpsertBulk) AddUID(v uint64) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.AddUID(v)
	})
}

// UpdateUID sets the "uid" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateUID() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateUID()
	})
}

// SetAliases sets the "aliases" field.
func (u *MailboxMessageUpsertBulk) SetAliases(v []string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetAliases(v)
	})
}

// UpdateAliases sets the "aliases" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateAliases() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateAliases()
	})
}

// SetFromAddress sets the "from_address" field.
func (u *MailboxMessageUpsertBulk) SetFromAddress(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetFromAddress(v)
	})
}

// UpdateFromAddress sets the "from_address" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateFromAddress() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateFromAddress()
	})
}

// SetSubject sets the "subject" field.
func (u *MailboxMessageUpsertBulk) SetSubject(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetSubject(v)
	})
}

// UpdateSubject sets the "subject" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateSubject() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateSubject()
	})
}

// SetMessageDate sets the "message_date" field.
func (u *MailboxMessageUpsertBulk) SetMessageDate(v float64) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetMessageDate(v)
	})
}

// AddMessageDate adds v to the "message_date" field.
func (u *MailboxMessageUpsertBulk) AddMessageDate(v float64) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.AddMessageDate(v)
	})
}

// UpdateMessageDate sets the "message_date" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateMessageDate() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateMessageDate()
	})
}

// SetText sets the "text" field.
func (u *MailboxMessageUpsertBulk) SetText(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetText(v)
	})
}

// UpdateText sets the "text" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateText() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateText()
	})
}

// SetSafeHTML sets the "safe_html" field.
func (u *MailboxMessageUpsertBulk) SetSafeHTML(v string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetSafeHTML(v)
	})
}

// UpdateSafeHTML sets the "safe_html" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateSafeHTML() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateSafeHTML()
	})
}

// SetCodes sets the "codes" field.
func (u *MailboxMessageUpsertBulk) SetCodes(v []string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetCodes(v)
	})
}

// UpdateCodes sets the "codes" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdateCodes() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdateCodes()
	})
}

// SetPartnerCodes sets the "partner_codes" field.
func (u *MailboxMessageUpsertBulk) SetPartnerCodes(v []string) *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.SetPartnerCodes(v)
	})
}

// UpdatePartnerCodes sets the "partner_codes" field to the value that was provided on create.
func (u *MailboxMessageUpsertBulk) UpdatePartnerCodes() *MailboxMessageUpsertBulk {
	return u.Update(func(s *MailboxMessageUpsert) {
		s.UpdatePartnerCodes()
	})
}

// Exec executes the query.
func (u *MailboxMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MailboxMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MailboxMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MailboxMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
