// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// MailboxMessageUpdate is the builder for updating MailboxMessage entities.
type MailboxMessageUpdate struct {
	config
	hooks    []Hook
	mutation *MailboxMessageMutation
}

// Where appends a list predicates to the MailboxMessageUpdate builder.
func (_u *MailboxMessageUpdate) Where(ps ...predicate.MailboxMessage) *MailboxMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *MailboxMessageUpdate) SetAccountID(v string) *MailboxMessageUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableAccountID(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *MailboxMessageUpdate) SetGeneration(v string) *MailboxMessageUpdate {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableGeneration(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetUID sets the "uid" field.
func (_u *MailboxMessageUpdate) SetUID(v uint64) *MailboxMessageUpdate {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableUID(v *uint64) *MailboxMessageUpdate {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *MailboxMessageUpdate) AddUID(v int64) *MailboxMessageUpdate {
	_u.mutation.AddUID(v)
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *MailboxMessageUpdate) SetAliases(v []string) *MailboxMessageUpdate {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *MailboxMessageUpdate) AppendAliases(v []string) *MailboxMessageUpdate {
	_u.mutation.AppendAliases(v)
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *MailboxMessageUpdate) SetFromAddress(v string) *MailboxMessageUpdate {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableFromAddress(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailboxMessageUpdate) SetSubject(v string) *MailboxMessageUpdate {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableSubject(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetMessageDate sets the "message_date" field.
func (_u *MailboxMessageUpdate) SetMessageDate(v float64) *MailboxMessageUpdate {
	_u.mutation.ResetMessageDate()
	_u.mutation.SetMessageDate(v)
	return _u
}

// SetNillableMessageDate sets the "message_date" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableMessageDate(v *float64) *MailboxMessageUpdate {
	if v != nil {
		_u.SetMessageDate(*v)
	}
	return _u
}

// AddMessageDate adds value to the "message_date" field.
func (_u *MailboxMessageUpdate) AddMessageDate(v float64) *MailboxMessageUpdate {
	_u.mutation.AddMessageDate(v)
	return _u
}

// SetText sets the "text" field.
func (_u *MailboxMessageUpdate) SetText(v string) *MailboxMessageUpdate {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableText(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSafeHTML sets the "safe_html" field.
func (_u *MailboxMessageUpdate) SetSafeHTML(v string) *MailboxMessageUpdate {
	_u.mutation.SetSafeHTML(v)
	return _u
}

// SetNillableSafeHTML sets the "safe_html" field if the given value is not nil.
func (_u *MailboxMessageUpdate) SetNillableSafeHTML(v *string) *MailboxMessageUpdate {
	if v != nil {
		_u.SetSafeHTML(*v)
	}
	return _u
}

// SetCodes sets the "codes" field.
func (_u *MailboxMessageUpdate) SetCodes(v []string) *MailboxMessageUpdate {
	_u.mutation.SetCodes(v)
	return _u
}

// AppendCodes appends value to the "codes" field.
func (_u *MailboxMessageUpdate) AppendCodes(v []string) *MailboxMessageUpdate {
	_u.mutation.AppendCodes(v)
	return _u
}

// SetPartnerCodes sets the "partner_codes" field.
func (_u *MailboxMessageUpdate) SetPartnerCodes(v []string) *MailboxMessageUpdate {
	_u.mutation.SetPartnerCodes(v)
	return _u
}

// AppendPartnerCodes appends value to the "partner_codes" field.
func (_u *MailboxMessageUpdate) AppendPartnerCodes(v []string) *MailboxMessageUpdate {
	_u.mutation.AppendPartnerCodes(v)
	return _u
}

// Mutation returns the MailboxMessageMutation object of the builder.
func (_u *MailboxMessageUpdate) Mutation() *MailboxMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MailboxMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailboxMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MailboxMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailboxMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailboxMessageUpdate) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mailboxmessage.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := mailboxmessage.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := mailboxmessage.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := mailboxmessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *MailboxMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailboxmessage.Table, mailboxmessage.Columns, sqlgraph.NewFieldSpec(mailboxmessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mailboxmessage.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(mailboxmessage.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(mailboxmessage.FieldUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(mailboxmessage.FieldUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(mailboxmessage.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldAliases, value)
		})
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(mailboxmessage.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(mailboxmessage.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageDate(); ok {
		_spec.SetField(mailboxmessage.FieldMessageDate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMessageDate(); ok {
		_spec.AddField(mailboxmessage.FieldMessageDate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(mailboxmessage.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SafeHTML(); ok {
		_spec.SetField(mailboxmessage.FieldSafeHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Codes(); ok {
		_spec.SetField(mailboxmessage.FieldCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldCodes, value)
		})
	}
	if value, ok := _u.mutation.PartnerCodes(); ok {
		_spec.SetField(mailboxmessage.FieldPartnerCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPartnerCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldPartnerCodes, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MailboxMessageUpdateOne is the builder for updating a single MailboxMessage entity.
type MailboxMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MailboxMessageMutation
}

// SetAccountID sets the "account_id" field.
func (_u *MailboxMessageUpdateOne) SetAccountID(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableAccountID(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGeneration sets the "generation" field.
func (_u *MailboxMessageUpdateOne) SetGeneration(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetGeneration(v)
	return _u
}

// SetNillableGeneration sets the "generation" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableGeneration(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetGeneration(*v)
	}
	return _u
}

// SetUID sets the "uid" field.
func (_u *MailboxMessageUpdateOne) SetUID(v uint64) *MailboxMessageUpdateOne {
	_u.mutation.ResetUID()
	_u.mutation.SetUID(v)
	return _u
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableUID(v *uint64) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetUID(*v)
	}
	return _u
}

// AddUID adds value to the "uid" field.
func (_u *MailboxMessageUpdateOne) AddUID(v int64) *MailboxMessageUpdateOne {
	_u.mutation.AddUID(v)
	return _u
}

// SetAliases sets the "aliases" field.
func (_u *MailboxMessageUpdateOne) SetAliases(v []string) *MailboxMessageUpdateOne {
	_u.mutation.SetAliases(v)
	return _u
}

// AppendAliases appends value to the "aliases" field.
func (_u *MailboxMessageUpdateOne) AppendAliases(v []string) *MailboxMessageUpdateOne {
	_u.mutation.AppendAliases(v)
	return _u
}

// SetFromAddress sets the "from_address" field.
func (_u *MailboxMessageUpdateOne) SetFromAddress(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetFromAddress(v)
	return _u
}

// SetNillableFromAddress sets the "from_address" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableFromAddress(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetFromAddress(*v)
	}
	return _u
}

// SetSubject sets the "subject" field.
func (_u *MailboxMessageUpdateOne) SetSubject(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetSubject(v)
	return _u
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableSubject(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetSubject(*v)
	}
	return _u
}

// SetMessageDate sets the "message_date" field.
func (_u *MailboxMessageUpdateOne) SetMessageDate(v float64) *MailboxMessageUpdateOne {
	_u.mutation.ResetMessageDate()
	_u.mutation.SetMessageDate(v)
	return _u
}

// SetNillableMessageDate sets the "message_date" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableMessageDate(v *float64) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetMessageDate(*v)
	}
	return _u
}

// AddMessageDate adds value to the "message_date" field.
func (_u *MailboxMessageUpdateOne) AddMessageDate(v float64) *MailboxMessageUpdateOne {
	_u.mutation.AddMessageDate(v)
	return _u
}

// SetText sets the "text" field.
func (_u *MailboxMessageUpdateOne) SetText(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetText(v)
	return _u
}

// SetNillableText sets the "text" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableText(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetText(*v)
	}
	return _u
}

// SetSafeHTML sets the "safe_html" field.
func (_u *MailboxMessageUpdateOne) SetSafeHTML(v string) *MailboxMessageUpdateOne {
	_u.mutation.SetSafeHTML(v)
	return _u
}

// SetNillableSafeHTML sets the "safe_html" field if the given value is not nil.
func (_u *MailboxMessageUpdateOne) SetNillableSafeHTML(v *string) *MailboxMessageUpdateOne {
	if v != nil {
		_u.SetSafeHTML(*v)
	}
	return _u
}

// SetCodes sets the "codes" field.
func (_u *MailboxMessageUpdateOne) SetCodes(v []string) *MailboxMessageUpdateOne {
	_u.mutation.SetCodes(v)
	return _u
}

// AppendCodes appends value to the "codes" field.
func (_u *MailboxMessageUpdateOne) AppendCodes(v []string) *MailboxMessageUpdateOne {
	_u.mutation.AppendCodes(v)
	return _u
}

// SetPartnerCodes sets the "partner_codes" field.
func (_u *MailboxMessageUpdateOne) SetPartnerCodes(v []string) *MailboxMessageUpdateOne {
	_u.mutation.SetPartnerCodes(v)
	return _u
}

// AppendPartnerCodes appends value to the "partner_codes" field.
func (_u *MailboxMessageUpdateOne) AppendPartnerCodes(v []string) *MailboxMessageUpdateOne {
	_u.mutation.AppendPartnerCodes(v)
	return _u
}

// Mutation returns the MailboxMessageMutation object of the builder.
func (_u *MailboxMessageUpdateOne) Mutation() *MailboxMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the MailboxMessageUpdate builder.
func (_u *MailboxMessageUpdateOne) Where(ps ...predicate.MailboxMessage) *MailboxMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MailboxMessageUpdateOne) Select(field string, fields ...string) *MailboxMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MailboxMessage entity.
func (_u *MailboxMessageUpdateOne) Save(ctx context.Context) (*MailboxMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MailboxMessageUpdateOne) SaveX(ctx context.Context) *MailboxMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MailboxMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MailboxMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MailboxMessageUpdateOne) check() error {
	if v, ok := _u.mutation.AccountID(); ok {
		if err := mailboxmessage.AccountIDValidator(v); err != nil {
			return &ValidationError{Name: "account_id", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.account_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generation(); ok {
		if err := mailboxmessage.GenerationValidator(v); err != nil {
			return &ValidationError{Name: "generation", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.generation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FromAddress(); ok {
		if err := mailboxmessage.FromAddressValidator(v); err != nil {
			return &ValidationError{Name: "from_address", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.from_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Subject(); ok {
		if err := mailboxmessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "MailboxMessage.subject": %w`, err)}
		}
	}
	return nil
}

func (_u *MailboxMessageUpdateOne) sqlSave(ctx context.Context) (_node *MailboxMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(mailboxmessage.Table, mailboxmessage.Columns, sqlgraph.NewFieldSpec(mailboxmessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MailboxMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mailboxmessage.FieldID)
		for _, f := range fields {
			if !mailboxmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != mailboxmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(mailboxmessage.FieldAccountID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Generation(); ok {
		_spec.SetField(mailboxmessage.FieldGeneration, field.TypeString, value)
	}
	if value, ok := _u.mutation.UID(); ok {
		_spec.SetField(mailboxmessage.FieldUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUID(); ok {
		_spec.AddField(mailboxmessage.FieldUID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Aliases(); ok {
		_spec.SetField(mailboxmessage.FieldAliases, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAliases(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldAliases, value)
		})
	}
	if value, ok := _u.mutation.FromAddress(); ok {
		_spec.SetField(mailboxmessage.FieldFromAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subject(); ok {
		_spec.SetField(mailboxmessage.FieldSubject, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageDate(); ok {
		_spec.SetField(mailboxmessage.FieldMessageDate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMessageDate(); ok {
		_spec.AddField(mailboxmessage.FieldMessageDate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Text(); ok {
		_spec.SetField(mailboxmessage.FieldText, field.TypeString, value)
	}
	if value, ok := _u.mutation.SafeHTML(); ok {
		_spec.SetField(mailboxmessage.FieldSafeHTML, field.TypeString, value)
	}
	if value, ok := _u.mutation.Codes(); ok {
		_spec.SetField(mailboxmessage.FieldCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldCodes, value)
		})
	}
	if value, ok := _u.mutation.PartnerCodes(); ok {
		_spec.SetField(mailboxmessage.FieldPartnerCodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPartnerCodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, mailboxmessage.FieldPartnerCodes, value)
		})
	}
	_node = &MailboxMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{mailboxmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
