// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
)

// MailboxMessage is the model entity for the MailboxMessage schema.
type MailboxMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID string `json:"account_id,omitempty"`
	// Generation holds the value of the "generation" field.
	Generation string `json:"generation,omitempty"`
	// UID holds the value of the "uid" field.
	UID uint64 `json:"uid,omitempty"`
	// Aliases holds the value of the "aliases" field.
	Aliases []string `json:"aliases,omitempty"`
	// FromAddress holds the value of the "from_address" field.
	FromAddress string `json:"from_address,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// MessageDate holds the value of the "message_date" field.
	MessageDate float64 `json:"message_date,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// SafeHTML holds the value of the "safe_html" field.
	SafeHTML string `json:"safe_html,omitempty"`
	// Codes holds the value of the "codes" field.
	Codes []string `json:"codes,omitempty"`
	// PartnerCodes holds the value of the "partner_codes" field.
	PartnerCodes []string `json:"partner_codes,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MailboxMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mailboxmessage.FieldAliases, mailboxmessage.FieldCodes, mailboxmessage.FieldPartnerCodes:
			values[i] = new([]byte)
		case mailboxmessage.FieldMessageDate:
			values[i] = new(sql.NullFloat64)
		case mailboxmessage.FieldID, mailboxmessage.FieldUID:
			values[i] = new(sql.NullInt64)
		case mailboxmessage.FieldAccountID, mailboxmessage.FieldGeneration, mailboxmessage.FieldFromAddress, mailboxmessage.FieldSubject, mailboxmessage.FieldText, mailboxmessage.FieldSafeHTML:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MailboxMessage fields.
func (_m *MailboxMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mailboxmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case mailboxmessage.FieldAccountID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.String
			}
		case mailboxmessage.FieldGeneration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field generation", values[i])
			} else if value.Valid {
				_m.Generation = value.String
			}
		case mailboxmessage.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				_m.UID = uint64(value.Int64)
			}
		case mailboxmessage.FieldAliases:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field aliases", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Aliases); err != nil {
					return fmt.Errorf("unmarshal field aliases: %w", err)
				}
			}
		case mailboxmessage.FieldFromAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_address", values[i])
			} else if value.Valid {
				_m.FromAddress = value.String
			}
		case mailboxmessage.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				_m.Subject = value.String
			}
		case mailboxmessage.FieldMessageDate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field message_date", values[i])
			} else if value.Valid {
				_m.MessageDate = value.Float64
			}
		case mailboxmessage.FieldText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[i])
			} else if value.Valid {
				_m.Text = value.String
			}
		case mailboxmessage.FieldSafeHTML:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field safe_html", values[i])
			} else if value.Valid {
				_m.SafeHTML = value.String
			}
		case mailboxmessage.FieldCodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field codes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Codes); err != nil {
					return fmt.Errorf("unmarshal field codes: %w", err)
				}
			}
		case mailboxmessage.FieldPartnerCodes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field partner_codes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PartnerCodes); err != nil {
					return fmt.Errorf("unmarshal field partner_codes: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MailboxMessage.
// This includes values selected through modifiers, order, etc.
func (_m *MailboxMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MailboxMessage.
// Note that you need to call MailboxMessage.Unwrap() before calling this method if this MailboxMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MailboxMessage) Update() *MailboxMessageUpdateOne {
	return NewMailboxMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MailboxMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MailboxMessage) Unwrap() *MailboxMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MailboxMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MailboxMessage) String() string {
	var builder strings.Builder
	builder.WriteString("MailboxMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(_m.AccountID)
	builder.WriteString(", ")
	builder.WriteString("generation=")
	builder.WriteString(_m.Generation)
	builder.WriteString(", ")
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", _m.UID))
	builder.WriteString(", ")
	builder.WriteString("aliases=")
	builder.WriteString(fmt.Sprintf("%v", _m.Aliases))
	builder.WriteString(", ")
	builder.WriteString("from_address=")
	builder.WriteString(_m.FromAddress)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(_m.Subject)
	builder.WriteString(", ")
	builder.WriteString("message_date=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageDate))
	builder.WriteString(", ")
	builder.WriteString("text=")
	builder.WriteString(_m.Text)
	builder.WriteString(", ")
	builder.WriteString("safe_html=")
	builder.WriteString(_m.SafeHTML)
	builder.WriteString(", ")
	builder.WriteString("codes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Codes))
	builder.WriteString(", ")
	builder.WriteString("partner_codes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PartnerCodes))
	builder.WriteByte(')')
	return builder.String()
}

// MailboxMessages is a parsable slice of MailboxMessage.
type MailboxMessages []*MailboxMessage
