// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/activitylog"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authapitoken"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authloginevent"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authsession"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/authuser"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailaliasappstate"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxhiddenmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxsyncstate"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activitylogFields := schema.ActivityLog{}.Fields()
	_ = activitylogFields
	// activitylogDescModule is the schema descriptor for module field.
	activitylogDescModule := activitylogFields[0].Descriptor()
	// activitylog.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	activitylog.ModuleValidator = func() func(string) error {
		validators := activitylogDescModule.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(module string) error {
			for _, fn := range fns {
				if err := fn(module); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescAccountID is the schema descriptor for account_id field.
	activitylogDescAccountID := activitylogFields[1].Descriptor()
	// activitylog.DefaultAccountID holds the default value on creation for the account_id field.
	activitylog.DefaultAccountID = activitylogDescAccountID.Default.(string)
	// activitylog.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	activitylog.AccountIDValidator = activitylogDescAccountID.Validators[0].(func(string) error)
	// activitylogDescCategory is the schema descriptor for category field.
	activitylogDescCategory := activitylogFields[2].Descriptor()
	// activitylog.CategoryValidator is a validator for the "category" field. It is called by the builders before save.
	activitylog.CategoryValidator = func() func(string) error {
		validators := activitylogDescCategory.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(category string) error {
			for _, fn := range fns {
				if err := fn(category); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescAction is the schema descriptor for action field.
	activitylogDescAction := activitylogFields[3].Descriptor()
	// activitylog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	activitylog.ActionValidator = func() func(string) error {
		validators := activitylogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescLevel is the schema descriptor for level field.
	activitylogDescLevel := activitylogFields[4].Descriptor()
	// activitylog.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	activitylog.LevelValidator = func() func(string) error {
		validators := activitylogDescLevel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(level string) error {
			for _, fn := range fns {
				if err := fn(level); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescOutcome is the schema descriptor for outcome field.
	activitylogDescOutcome := activitylogFields[5].Descriptor()
	// activitylog.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	activitylog.OutcomeValidator = func() func(string) error {
		validators := activitylogDescOutcome.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(outcome string) error {
			for _, fn := range fns {
				if err := fn(outcome); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescSummary is the schema descriptor for summary field.
	activitylogDescSummary := activitylogFields[6].Descriptor()
	// activitylog.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	activitylog.SummaryValidator = func() func(string) error {
		validators := activitylogDescSummary.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(summary string) error {
			for _, fn := range fns {
				if err := fn(summary); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescSource is the schema descriptor for source field.
	activitylogDescSource := activitylogFields[7].Descriptor()
	// activitylog.SourceValidator is a validator for the "source" field. It is called by the builders before save.
	activitylog.SourceValidator = func() func(string) error {
		validators := activitylogDescSource.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(source string) error {
			for _, fn := range fns {
				if err := fn(source); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitylogDescMethod is the schema descriptor for method field.
	activitylogDescMethod := activitylogFields[8].Descriptor()
	// activitylog.DefaultMethod holds the default value on creation for the method field.
	activitylog.DefaultMethod = activitylogDescMethod.Default.(string)
	// activitylog.MethodValidator is a validator for the "method" field. It is called by the builders before save.
	activitylog.MethodValidator = activitylogDescMethod.Validators[0].(func(string) error)
	// activitylogDescPath is the schema descriptor for path field.
	activitylogDescPath := activitylogFields[9].Descriptor()
	// activitylog.DefaultPath holds the default value on creation for the path field.
	activitylog.DefaultPath = activitylogDescPath.Default.(string)
	// activitylog.PathValidator is a validator for the "path" field. It is called by the builders before save.
	activitylog.PathValidator = activitylogDescPath.Validators[0].(func(string) error)
	// activitylogDescHTTPStatus is the schema descriptor for http_status field.
	activitylogDescHTTPStatus := activitylogFields[10].Descriptor()
	// activitylog.DefaultHTTPStatus holds the default value on creation for the http_status field.
	activitylog.DefaultHTTPStatus = activitylogDescHTTPStatus.Default.(int)
	// activitylogDescDurationMs is the schema descriptor for duration_ms field.
	activitylogDescDurationMs := activitylogFields[11].Descriptor()
	// activitylog.DefaultDurationMs holds the default value on creation for the duration_ms field.
	activitylog.DefaultDurationMs = activitylogDescDurationMs.Default.(int64)
	// activitylogDescRequestID is the schema descriptor for request_id field.
	activitylogDescRequestID := activitylogFields[12].Descriptor()
	// activitylog.DefaultRequestID holds the default value on creation for the request_id field.
	activitylog.DefaultRequestID = activitylogDescRequestID.Default.(string)
	// activitylog.RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	activitylog.RequestIDValidator = activitylogDescRequestID.Validators[0].(func(string) error)
	// activitylogDescDetail is the schema descriptor for detail field.
	activitylogDescDetail := activitylogFields[13].Descriptor()
	// activitylog.DefaultDetail holds the default value on creation for the detail field.
	activitylog.DefaultDetail = activitylogDescDetail.Default.(string)
	// activitylog.DetailValidator is a validator for the "detail" field. It is called by the builders before save.
	activitylog.DetailValidator = activitylogDescDetail.Validators[0].(func(string) error)
	// activitylogDescMetadata is the schema descriptor for metadata field.
	activitylogDescMetadata := activitylogFields[14].Descriptor()
	// activitylog.DefaultMetadata holds the default value on creation for the metadata field.
	activitylog.DefaultMetadata = activitylogDescMetadata.Default.(map[string]interface{})
	// activitylogDescCreatedAt is the schema descriptor for created_at field.
	activitylogDescCreatedAt := activitylogFields[15].Descriptor()
	// activitylog.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitylog.DefaultCreatedAt = activitylogDescCreatedAt.Default.(func() time.Time)
	authapitokenFields := schema.AuthAPIToken{}.Fields()
	_ = authapitokenFields
	// authapitokenDescName is the schema descriptor for name field.
	authapitokenDescName := authapitokenFields[2].Descriptor()
	// authapitoken.NameValidator is a validator for the "name" field. It is called by the builders before save.
	authapitoken.NameValidator = func() func(string) error {
		validators := authapitokenDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// authapitokenDescTokenHash is the schema descriptor for token_hash field.
	authapitokenDescTokenHash := authapitokenFields[3].Descriptor()
	// authapitoken.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	authapitoken.TokenHashValidator = authapitokenDescTokenHash.Validators[0].(func(string) error)
	// authapitokenDescTokenPrefix is the schema descriptor for token_prefix field.
	authapitokenDescTokenPrefix := authapitokenFields[4].Descriptor()
	// authapitoken.TokenPrefixValidator is a validator for the "token_prefix" field. It is called by the builders before save.
	authapitoken.TokenPrefixValidator = authapitokenDescTokenPrefix.Validators[0].(func(string) error)
	// authapitokenDescCreatedAt is the schema descriptor for created_at field.
	authapitokenDescCreatedAt := authapitokenFields[5].Descriptor()
	// authapitoken.DefaultCreatedAt holds the default value on creation for the created_at field.
	authapitoken.DefaultCreatedAt = authapitokenDescCreatedAt.Default.(func() time.Time)
	// authapitokenDescID is the schema descriptor for id field.
	authapitokenDescID := authapitokenFields[0].Descriptor()
	// authapitoken.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authapitoken.IDValidator = authapitokenDescID.Validators[0].(func(string) error)
	authlogineventFields := schema.AuthLoginEvent{}.Fields()
	_ = authlogineventFields
	// authlogineventDescUsername is the schema descriptor for username field.
	authlogineventDescUsername := authlogineventFields[2].Descriptor()
	// authloginevent.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	authloginevent.UsernameValidator = authlogineventDescUsername.Validators[0].(func(string) error)
	// authlogineventDescOutcome is the schema descriptor for outcome field.
	authlogineventDescOutcome := authlogineventFields[3].Descriptor()
	// authloginevent.OutcomeValidator is a validator for the "outcome" field. It is called by the builders before save.
	authloginevent.OutcomeValidator = authlogineventDescOutcome.Validators[0].(func(string) error)
	// authlogineventDescReason is the schema descriptor for reason field.
	authlogineventDescReason := authlogineventFields[4].Descriptor()
	// authloginevent.DefaultReason holds the default value on creation for the reason field.
	authloginevent.DefaultReason = authlogineventDescReason.Default.(string)
	// authloginevent.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	authloginevent.ReasonValidator = authlogineventDescReason.Validators[0].(func(string) error)
	// authlogineventDescIPAddress is the schema descriptor for ip_address field.
	authlogineventDescIPAddress := authlogineventFields[5].Descriptor()
	// authloginevent.DefaultIPAddress holds the default value on creation for the ip_address field.
	authloginevent.DefaultIPAddress = authlogineventDescIPAddress.Default.(string)
	// authloginevent.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	authloginevent.IPAddressValidator = authlogineventDescIPAddress.Validators[0].(func(string) error)
	// authlogineventDescUserAgent is the schema descriptor for user_agent field.
	authlogineventDescUserAgent := authlogineventFields[6].Descriptor()
	// authloginevent.DefaultUserAgent holds the default value on creation for the user_agent field.
	authloginevent.DefaultUserAgent = authlogineventDescUserAgent.Default.(string)
	// authloginevent.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	authloginevent.UserAgentValidator = authlogineventDescUserAgent.Validators[0].(func(string) error)
	// authlogineventDescCreatedAt is the schema descriptor for created_at field.
	authlogineventDescCreatedAt := authlogineventFields[7].Descriptor()
	// authloginevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	authloginevent.DefaultCreatedAt = authlogineventDescCreatedAt.Default.(func() time.Time)
	authsessionFields := schema.AuthSession{}.Fields()
	_ = authsessionFields
	// authsessionDescIPAddress is the schema descriptor for ip_address field.
	authsessionDescIPAddress := authsessionFields[2].Descriptor()
	// authsession.DefaultIPAddress holds the default value on creation for the ip_address field.
	authsession.DefaultIPAddress = authsessionDescIPAddress.Default.(string)
	// authsession.IPAddressValidator is a validator for the "ip_address" field. It is called by the builders before save.
	authsession.IPAddressValidator = authsessionDescIPAddress.Validators[0].(func(string) error)
	// authsessionDescUserAgent is the schema descriptor for user_agent field.
	authsessionDescUserAgent := authsessionFields[3].Descriptor()
	// authsession.DefaultUserAgent holds the default value on creation for the user_agent field.
	authsession.DefaultUserAgent = authsessionDescUserAgent.Default.(string)
	// authsession.UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	authsession.UserAgentValidator = authsessionDescUserAgent.Validators[0].(func(string) error)
	// authsessionDescCreatedAt is the schema descriptor for created_at field.
	authsessionDescCreatedAt := authsessionFields[4].Descriptor()
	// authsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	authsession.DefaultCreatedAt = authsessionDescCreatedAt.Default.(func() time.Time)
	// authsessionDescLastSeenAt is the schema descriptor for last_seen_at field.
	authsessionDescLastSeenAt := authsessionFields[5].Descriptor()
	// authsession.DefaultLastSeenAt holds the default value on creation for the last_seen_at field.
	authsession.DefaultLastSeenAt = authsessionDescLastSeenAt.Default.(func() time.Time)
	// authsessionDescID is the schema descriptor for id field.
	authsessionDescID := authsessionFields[0].Descriptor()
	// authsession.IDValidator is a validator for the "id" field. It is called by the builders before save.
	authsession.IDValidator = authsessionDescID.Validators[0].(func(string) error)
	authuserFields := schema.AuthUser{}.Fields()
	_ = authuserFields
	// authuserDescUsername is the schema descriptor for username field.
	authuserDescUsername := authuserFields[1].Descriptor()
	// authuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	authuser.UsernameValidator = func() func(string) error {
		validators := authuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// authuserDescMustChangePassword is the schema descriptor for must_change_password field.
	authuserDescMustChangePassword := authuserFields[3].Descriptor()
	// authuser.DefaultMustChangePassword holds the default value on creation for the must_change_password field.
	authuser.DefaultMustChangePassword = authuserDescMustChangePassword.Default.(bool)
	// authuserDescDisabled is the schema descriptor for disabled field.
	authuserDescDisabled := authuserFields[4].Descriptor()
	// authuser.DefaultDisabled holds the default value on creation for the disabled field.
	authuser.DefaultDisabled = authuserDescDisabled.Default.(bool)
	// authuserDescCreatedAt is the schema descriptor for created_at field.
	authuserDescCreatedAt := authuserFields[5].Descriptor()
	// authuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	authuser.DefaultCreatedAt = authuserDescCreatedAt.Default.(func() time.Time)
	// authuserDescUpdatedAt is the schema descriptor for updated_at field.
	authuserDescUpdatedAt := authuserFields[6].Descriptor()
	// authuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	authuser.DefaultUpdatedAt = authuserDescUpdatedAt.Default.(func() time.Time)
	// authuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	authuser.UpdateDefaultUpdatedAt = authuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	mailaliasappstateFields := schema.MailAliasAppState{}.Fields()
	_ = mailaliasappstateFields
	// mailaliasappstateDescAccountID is the schema descriptor for account_id field.
	mailaliasappstateDescAccountID := mailaliasappstateFields[0].Descriptor()
	// mailaliasappstate.DefaultAccountID holds the default value on creation for the account_id field.
	mailaliasappstate.DefaultAccountID = mailaliasappstateDescAccountID.Default.(string)
	// mailaliasappstate.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mailaliasappstate.AccountIDValidator = mailaliasappstateDescAccountID.Validators[0].(func(string) error)
	// mailaliasappstateDescAlias is the schema descriptor for alias field.
	mailaliasappstateDescAlias := mailaliasappstateFields[1].Descriptor()
	// mailaliasappstate.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	mailaliasappstate.AliasValidator = func() func(string) error {
		validators := mailaliasappstateDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailaliasappstateDescAppKey is the schema descriptor for app_key field.
	mailaliasappstateDescAppKey := mailaliasappstateFields[2].Descriptor()
	// mailaliasappstate.AppKeyValidator is a validator for the "app_key" field. It is called by the builders before save.
	mailaliasappstate.AppKeyValidator = func() func(string) error {
		validators := mailaliasappstateDescAppKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(app_key string) error {
			for _, fn := range fns {
				if err := fn(app_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailaliasappstateDescStatus is the schema descriptor for status field.
	mailaliasappstateDescStatus := mailaliasappstateFields[3].Descriptor()
	// mailaliasappstate.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	mailaliasappstate.StatusValidator = func() func(string) error {
		validators := mailaliasappstateDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailaliasappstateDescDetectedUID is the schema descriptor for detected_uid field.
	mailaliasappstateDescDetectedUID := mailaliasappstateFields[5].Descriptor()
	// mailaliasappstate.DefaultDetectedUID holds the default value on creation for the detected_uid field.
	mailaliasappstate.DefaultDetectedUID = mailaliasappstateDescDetectedUID.Default.(uint64)
	// mailaliasappstateDescDetectedSubject is the schema descriptor for detected_subject field.
	mailaliasappstateDescDetectedSubject := mailaliasappstateFields[6].Descriptor()
	// mailaliasappstate.DefaultDetectedSubject holds the default value on creation for the detected_subject field.
	mailaliasappstate.DefaultDetectedSubject = mailaliasappstateDescDetectedSubject.Default.(string)
	// mailaliasappstate.DetectedSubjectValidator is a validator for the "detected_subject" field. It is called by the builders before save.
	mailaliasappstate.DetectedSubjectValidator = mailaliasappstateDescDetectedSubject.Validators[0].(func(string) error)
	// mailaliasappstateDescDetectedSender is the schema descriptor for detected_sender field.
	mailaliasappstateDescDetectedSender := mailaliasappstateFields[7].Descriptor()
	// mailaliasappstate.DefaultDetectedSender holds the default value on creation for the detected_sender field.
	mailaliasappstate.DefaultDetectedSender = mailaliasappstateDescDetectedSender.Default.(string)
	// mailaliasappstate.DetectedSenderValidator is a validator for the "detected_sender" field. It is called by the builders before save.
	mailaliasappstate.DetectedSenderValidator = mailaliasappstateDescDetectedSender.Validators[0].(func(string) error)
	// mailaliasappstateDescConfirmedUID is the schema descriptor for confirmed_uid field.
	mailaliasappstateDescConfirmedUID := mailaliasappstateFields[9].Descriptor()
	// mailaliasappstate.DefaultConfirmedUID holds the default value on creation for the confirmed_uid field.
	mailaliasappstate.DefaultConfirmedUID = mailaliasappstateDescConfirmedUID.Default.(uint64)
	// mailaliasappstateDescConfirmedSubject is the schema descriptor for confirmed_subject field.
	mailaliasappstateDescConfirmedSubject := mailaliasappstateFields[10].Descriptor()
	// mailaliasappstate.DefaultConfirmedSubject holds the default value on creation for the confirmed_subject field.
	mailaliasappstate.DefaultConfirmedSubject = mailaliasappstateDescConfirmedSubject.Default.(string)
	// mailaliasappstate.ConfirmedSubjectValidator is a validator for the "confirmed_subject" field. It is called by the builders before save.
	mailaliasappstate.ConfirmedSubjectValidator = mailaliasappstateDescConfirmedSubject.Validators[0].(func(string) error)
	// mailaliasappstateDescConfirmedSender is the schema descriptor for confirmed_sender field.
	mailaliasappstateDescConfirmedSender := mailaliasappstateFields[11].Descriptor()
	// mailaliasappstate.DefaultConfirmedSender holds the default value on creation for the confirmed_sender field.
	mailaliasappstate.DefaultConfirmedSender = mailaliasappstateDescConfirmedSender.Default.(string)
	// mailaliasappstate.ConfirmedSenderValidator is a validator for the "confirmed_sender" field. It is called by the builders before save.
	mailaliasappstate.ConfirmedSenderValidator = mailaliasappstateDescConfirmedSender.Validators[0].(func(string) error)
	// mailaliasappstateDescCreatedAt is the schema descriptor for created_at field.
	mailaliasappstateDescCreatedAt := mailaliasappstateFields[12].Descriptor()
	// mailaliasappstate.DefaultCreatedAt holds the default value on creation for the created_at field.
	mailaliasappstate.DefaultCreatedAt = mailaliasappstateDescCreatedAt.Default.(func() time.Time)
	// mailaliasappstateDescUpdatedAt is the schema descriptor for updated_at field.
	mailaliasappstateDescUpdatedAt := mailaliasappstateFields[13].Descriptor()
	// mailaliasappstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mailaliasappstate.DefaultUpdatedAt = mailaliasappstateDescUpdatedAt.Default.(func() time.Time)
	// mailaliasappstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mailaliasappstate.UpdateDefaultUpdatedAt = mailaliasappstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	mailboxhiddenmessageFields := schema.MailboxHiddenMessage{}.Fields()
	_ = mailboxhiddenmessageFields
	// mailboxhiddenmessageDescAccountID is the schema descriptor for account_id field.
	mailboxhiddenmessageDescAccountID := mailboxhiddenmessageFields[0].Descriptor()
	// mailboxhiddenmessage.DefaultAccountID holds the default value on creation for the account_id field.
	mailboxhiddenmessage.DefaultAccountID = mailboxhiddenmessageDescAccountID.Default.(string)
	// mailboxhiddenmessage.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mailboxhiddenmessage.AccountIDValidator = mailboxhiddenmessageDescAccountID.Validators[0].(func(string) error)
	// mailboxhiddenmessageDescGeneration is the schema descriptor for generation field.
	mailboxhiddenmessageDescGeneration := mailboxhiddenmessageFields[1].Descriptor()
	// mailboxhiddenmessage.GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	mailboxhiddenmessage.GenerationValidator = func() func(string) error {
		validators := mailboxhiddenmessageDescGeneration.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(generation string) error {
			for _, fn := range fns {
				if err := fn(generation); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxhiddenmessageDescAlias is the schema descriptor for alias field.
	mailboxhiddenmessageDescAlias := mailboxhiddenmessageFields[2].Descriptor()
	// mailboxhiddenmessage.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	mailboxhiddenmessage.AliasValidator = func() func(string) error {
		validators := mailboxhiddenmessageDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	mailboxmessageFields := schema.MailboxMessage{}.Fields()
	_ = mailboxmessageFields
	// mailboxmessageDescAccountID is the schema descriptor for account_id field.
	mailboxmessageDescAccountID := mailboxmessageFields[0].Descriptor()
	// mailboxmessage.DefaultAccountID holds the default value on creation for the account_id field.
	mailboxmessage.DefaultAccountID = mailboxmessageDescAccountID.Default.(string)
	// mailboxmessage.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mailboxmessage.AccountIDValidator = mailboxmessageDescAccountID.Validators[0].(func(string) error)
	// mailboxmessageDescGeneration is the schema descriptor for generation field.
	mailboxmessageDescGeneration := mailboxmessageFields[1].Descriptor()
	// mailboxmessage.GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	mailboxmessage.GenerationValidator = func() func(string) error {
		validators := mailboxmessageDescGeneration.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(generation string) error {
			for _, fn := range fns {
				if err := fn(generation); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxmessageDescAliases is the schema descriptor for aliases field.
	mailboxmessageDescAliases := mailboxmessageFields[3].Descriptor()
	// mailboxmessage.DefaultAliases holds the default value on creation for the aliases field.
	mailboxmessage.DefaultAliases = mailboxmessageDescAliases.Default.([]string)
	// mailboxmessageDescFromAddress is the schema descriptor for from_address field.
	mailboxmessageDescFromAddress := mailboxmessageFields[4].Descriptor()
	// mailboxmessage.DefaultFromAddress holds the default value on creation for the from_address field.
	mailboxmessage.DefaultFromAddress = mailboxmessageDescFromAddress.Default.(string)
	// mailboxmessage.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	mailboxmessage.FromAddressValidator = mailboxmessageDescFromAddress.Validators[0].(func(string) error)
	// mailboxmessageDescSubject is the schema descriptor for subject field.
	mailboxmessageDescSubject := mailboxmessageFields[5].Descriptor()
	// mailboxmessage.DefaultSubject holds the default value on creation for the subject field.
	mailboxmessage.DefaultSubject = mailboxmessageDescSubject.Default.(string)
	// mailboxmessage.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	mailboxmessage.SubjectValidator = mailboxmessageDescSubject.Validators[0].(func(string) error)
	// mailboxmessageDescText is the schema descriptor for text field.
	mailboxmessageDescText := mailboxmessageFields[7].Descriptor()
	// mailboxmessage.DefaultText holds the default value on creation for the text field.
	mailboxmessage.DefaultText = mailboxmessageDescText.Default.(string)
	// mailboxmessageDescSafeHTML is the schema descriptor for safe_html field.
	mailboxmessageDescSafeHTML := mailboxmessageFields[8].Descriptor()
	// mailboxmessage.DefaultSafeHTML holds the default value on creation for the safe_html field.
	mailboxmessage.DefaultSafeHTML = mailboxmessageDescSafeHTML.Default.(string)
	// mailboxmessageDescCodes is the schema descriptor for codes field.
	mailboxmessageDescCodes := mailboxmessageFields[9].Descriptor()
	// mailboxmessage.DefaultCodes holds the default value on creation for the codes field.
	mailboxmessage.DefaultCodes = mailboxmessageDescCodes.Default.([]string)
	// mailboxmessageDescPartnerCodes is the schema descriptor for partner_codes field.
	mailboxmessageDescPartnerCodes := mailboxmessageFields[10].Descriptor()
	// mailboxmessage.DefaultPartnerCodes holds the default value on creation for the partner_codes field.
	mailboxmessage.DefaultPartnerCodes = mailboxmessageDescPartnerCodes.Default.([]string)
	mailboxsyncstateFields := schema.MailboxSyncState{}.Fields()
	_ = mailboxsyncstateFields
	// mailboxsyncstateDescAccountID is the schema descriptor for account_id field.
	mailboxsyncstateDescAccountID := mailboxsyncstateFields[0].Descriptor()
	// mailboxsyncstate.DefaultAccountID holds the default value on creation for the account_id field.
	mailboxsyncstate.DefaultAccountID = mailboxsyncstateDescAccountID.Default.(string)
	// mailboxsyncstate.AccountIDValidator is a validator for the "account_id" field. It is called by the builders before save.
	mailboxsyncstate.AccountIDValidator = mailboxsyncstateDescAccountID.Validators[0].(func(string) error)
	// mailboxsyncstateDescKey is the schema descriptor for key field.
	mailboxsyncstateDescKey := mailboxsyncstateFields[1].Descriptor()
	// mailboxsyncstate.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	mailboxsyncstate.KeyValidator = func() func(string) error {
		validators := mailboxsyncstateDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxsyncstateDescStatus is the schema descriptor for status field.
	mailboxsyncstateDescStatus := mailboxsyncstateFields[2].Descriptor()
	// mailboxsyncstate.DefaultStatus holds the default value on creation for the status field.
	mailboxsyncstate.DefaultStatus = mailboxsyncstateDescStatus.Default.(map[string]interface{})
	// mailboxsyncstateDescHighestUID is the schema descriptor for highest_uid field.
	mailboxsyncstateDescHighestUID := mailboxsyncstateFields[3].Descriptor()
	// mailboxsyncstate.DefaultHighestUID holds the default value on creation for the highest_uid field.
	mailboxsyncstate.DefaultHighestUID = mailboxsyncstateDescHighestUID.Default.(uint64)
	// mailboxsyncstateDescAllowedAliases is the schema descriptor for allowed_aliases field.
	mailboxsyncstateDescAllowedAliases := mailboxsyncstateFields[4].Descriptor()
	// mailboxsyncstate.DefaultAllowedAliases holds the default value on creation for the allowed_aliases field.
	mailboxsyncstate.DefaultAllowedAliases = mailboxsyncstateDescAllowedAliases.Default.([]string)
}
