// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxhiddenmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxmessage"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/mailboxsyncstate"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mailboxhiddenmessageFields := schema.MailboxHiddenMessage{}.Fields()
	_ = mailboxhiddenmessageFields
	// mailboxhiddenmessageDescGeneration is the schema descriptor for generation field.
	mailboxhiddenmessageDescGeneration := mailboxhiddenmessageFields[0].Descriptor()
	// mailboxhiddenmessage.GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	mailboxhiddenmessage.GenerationValidator = func() func(string) error {
		validators := mailboxhiddenmessageDescGeneration.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(generation string) error {
			for _, fn := range fns {
				if err := fn(generation); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxhiddenmessageDescAlias is the schema descriptor for alias field.
	mailboxhiddenmessageDescAlias := mailboxhiddenmessageFields[1].Descriptor()
	// mailboxhiddenmessage.AliasValidator is a validator for the "alias" field. It is called by the builders before save.
	mailboxhiddenmessage.AliasValidator = func() func(string) error {
		validators := mailboxhiddenmessageDescAlias.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(alias string) error {
			for _, fn := range fns {
				if err := fn(alias); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	mailboxmessageFields := schema.MailboxMessage{}.Fields()
	_ = mailboxmessageFields
	// mailboxmessageDescGeneration is the schema descriptor for generation field.
	mailboxmessageDescGeneration := mailboxmessageFields[0].Descriptor()
	// mailboxmessage.GenerationValidator is a validator for the "generation" field. It is called by the builders before save.
	mailboxmessage.GenerationValidator = func() func(string) error {
		validators := mailboxmessageDescGeneration.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(generation string) error {
			for _, fn := range fns {
				if err := fn(generation); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxmessageDescAliases is the schema descriptor for aliases field.
	mailboxmessageDescAliases := mailboxmessageFields[2].Descriptor()
	// mailboxmessage.DefaultAliases holds the default value on creation for the aliases field.
	mailboxmessage.DefaultAliases = mailboxmessageDescAliases.Default.([]string)
	// mailboxmessageDescFromAddress is the schema descriptor for from_address field.
	mailboxmessageDescFromAddress := mailboxmessageFields[3].Descriptor()
	// mailboxmessage.DefaultFromAddress holds the default value on creation for the from_address field.
	mailboxmessage.DefaultFromAddress = mailboxmessageDescFromAddress.Default.(string)
	// mailboxmessage.FromAddressValidator is a validator for the "from_address" field. It is called by the builders before save.
	mailboxmessage.FromAddressValidator = mailboxmessageDescFromAddress.Validators[0].(func(string) error)
	// mailboxmessageDescSubject is the schema descriptor for subject field.
	mailboxmessageDescSubject := mailboxmessageFields[4].Descriptor()
	// mailboxmessage.DefaultSubject holds the default value on creation for the subject field.
	mailboxmessage.DefaultSubject = mailboxmessageDescSubject.Default.(string)
	// mailboxmessage.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	mailboxmessage.SubjectValidator = mailboxmessageDescSubject.Validators[0].(func(string) error)
	// mailboxmessageDescText is the schema descriptor for text field.
	mailboxmessageDescText := mailboxmessageFields[6].Descriptor()
	// mailboxmessage.DefaultText holds the default value on creation for the text field.
	mailboxmessage.DefaultText = mailboxmessageDescText.Default.(string)
	// mailboxmessageDescSafeHTML is the schema descriptor for safe_html field.
	mailboxmessageDescSafeHTML := mailboxmessageFields[7].Descriptor()
	// mailboxmessage.DefaultSafeHTML holds the default value on creation for the safe_html field.
	mailboxmessage.DefaultSafeHTML = mailboxmessageDescSafeHTML.Default.(string)
	// mailboxmessageDescCodes is the schema descriptor for codes field.
	mailboxmessageDescCodes := mailboxmessageFields[8].Descriptor()
	// mailboxmessage.DefaultCodes holds the default value on creation for the codes field.
	mailboxmessage.DefaultCodes = mailboxmessageDescCodes.Default.([]string)
	// mailboxmessageDescPartnerCodes is the schema descriptor for partner_codes field.
	mailboxmessageDescPartnerCodes := mailboxmessageFields[9].Descriptor()
	// mailboxmessage.DefaultPartnerCodes holds the default value on creation for the partner_codes field.
	mailboxmessage.DefaultPartnerCodes = mailboxmessageDescPartnerCodes.Default.([]string)
	mailboxsyncstateFields := schema.MailboxSyncState{}.Fields()
	_ = mailboxsyncstateFields
	// mailboxsyncstateDescKey is the schema descriptor for key field.
	mailboxsyncstateDescKey := mailboxsyncstateFields[0].Descriptor()
	// mailboxsyncstate.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	mailboxsyncstate.KeyValidator = func() func(string) error {
		validators := mailboxsyncstateDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mailboxsyncstateDescStatus is the schema descriptor for status field.
	mailboxsyncstateDescStatus := mailboxsyncstateFields[1].Descriptor()
	// mailboxsyncstate.DefaultStatus holds the default value on creation for the status field.
	mailboxsyncstate.DefaultStatus = mailboxsyncstateDescStatus.Default.(map[string]interface{})
	// mailboxsyncstateDescHighestUID is the schema descriptor for highest_uid field.
	mailboxsyncstateDescHighestUID := mailboxsyncstateFields[2].Descriptor()
	// mailboxsyncstate.DefaultHighestUID holds the default value on creation for the highest_uid field.
	mailboxsyncstate.DefaultHighestUID = mailboxsyncstateDescHighestUID.Default.(uint64)
	// mailboxsyncstateDescAllowedAliases is the schema descriptor for allowed_aliases field.
	mailboxsyncstateDescAllowedAliases := mailboxsyncstateFields[3].Descriptor()
	// mailboxsyncstate.DefaultAllowedAliases holds the default value on creation for the allowed_aliases field.
	mailboxsyncstate.DefaultAllowedAliases = mailboxsyncstateDescAllowedAliases.Default.([]string)
}
