// Code generated by ent, DO NOT EDIT.

package mailboxhiddenmessage

import (
	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldAccountID, v))
}

// Generation applies equality check predicate on the "generation" field. It's identical to GenerationEQ.
func Generation(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldGeneration, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldAlias, v))
}

// UID applies equality check predicate on the "uid" field. It's identical to UIDEQ.
func UID(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldUID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContainsFold(FieldAccountID, v))
}

// GenerationEQ applies the EQ predicate on the "generation" field.
func GenerationEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldGeneration, v))
}

// GenerationNEQ applies the NEQ predicate on the "generation" field.
func GenerationNEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNEQ(FieldGeneration, v))
}

// GenerationIn applies the In predicate on the "generation" field.
func GenerationIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldIn(FieldGeneration, vs...))
}

// GenerationNotIn applies the NotIn predicate on the "generation" field.
func GenerationNotIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNotIn(FieldGeneration, vs...))
}

// GenerationGT applies the GT predicate on the "generation" field.
func GenerationGT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGT(FieldGeneration, v))
}

// GenerationGTE applies the GTE predicate on the "generation" field.
func GenerationGTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGTE(FieldGeneration, v))
}

// GenerationLT applies the LT predicate on the "generation" field.
func GenerationLT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLT(FieldGeneration, v))
}

// GenerationLTE applies the LTE predicate on the "generation" field.
func GenerationLTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLTE(FieldGeneration, v))
}

// GenerationContains applies the Contains predicate on the "generation" field.
func GenerationContains(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContains(FieldGeneration, v))
}

// GenerationHasPrefix applies the HasPrefix predicate on the "generation" field.
func GenerationHasPrefix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasPrefix(FieldGeneration, v))
}

// GenerationHasSuffix applies the HasSuffix predicate on the "generation" field.
func GenerationHasSuffix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasSuffix(FieldGeneration, v))
}

// GenerationEqualFold applies the EqualFold predicate on the "generation" field.
func GenerationEqualFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEqualFold(FieldGeneration, v))
}

// GenerationContainsFold applies the ContainsFold predicate on the "generation" field.
func GenerationContainsFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContainsFold(FieldGeneration, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldContainsFold(FieldAlias, v))
}

// UIDEQ applies the EQ predicate on the "uid" field.
func UIDEQ(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldEQ(FieldUID, v))
}

// UIDNEQ applies the NEQ predicate on the "uid" field.
func UIDNEQ(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNEQ(FieldUID, v))
}

// UIDIn applies the In predicate on the "uid" field.
func UIDIn(vs ...uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldIn(FieldUID, vs...))
}

// UIDNotIn applies the NotIn predicate on the "uid" field.
func UIDNotIn(vs ...uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldNotIn(FieldUID, vs...))
}

// UIDGT applies the GT predicate on the "uid" field.
func UIDGT(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGT(FieldUID, v))
}

// UIDGTE applies the GTE predicate on the "uid" field.
func UIDGTE(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldGTE(FieldUID, v))
}

// UIDLT applies the LT predicate on the "uid" field.
func UIDLT(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLT(FieldUID, v))
}

// UIDLTE applies the LTE predicate on the "uid" field.
func UIDLTE(v uint64) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.FieldLTE(FieldUID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MailboxHiddenMessage) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MailboxHiddenMessage) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MailboxHiddenMessage) predicate.MailboxHiddenMessage {
	return predicate.MailboxHiddenMessage(sql.NotPredicates(p))
}
