// Code generated by ent, DO NOT EDIT.

package activitylog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Bringbasket/running-tools/internal/platform/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldID, id))
}

// Module applies equality check predicate on the "module" field. It's identical to ModuleEQ.
func Module(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldModule, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldAccountID, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldCategory, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldAction, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldLevel, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldOutcome, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldSummary, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldSource, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldMethod, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldPath, v))
}

// HTTPStatus applies equality check predicate on the "http_status" field. It's identical to HTTPStatusEQ.
func HTTPStatus(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldHTTPStatus, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldDurationMs, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldRequestID, v))
}

// Detail applies equality check predicate on the "detail" field. It's identical to DetailEQ.
func Detail(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldDetail, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldCreatedAt, v))
}

// ModuleEQ applies the EQ predicate on the "module" field.
func ModuleEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldModule, v))
}

// ModuleNEQ applies the NEQ predicate on the "module" field.
func ModuleNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldModule, v))
}

// ModuleIn applies the In predicate on the "module" field.
func ModuleIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldModule, vs...))
}

// ModuleNotIn applies the NotIn predicate on the "module" field.
func ModuleNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldModule, vs...))
}

// ModuleGT applies the GT predicate on the "module" field.
func ModuleGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldModule, v))
}

// ModuleGTE applies the GTE predicate on the "module" field.
func ModuleGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldModule, v))
}

// ModuleLT applies the LT predicate on the "module" field.
func ModuleLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldModule, v))
}

// ModuleLTE applies the LTE predicate on the "module" field.
func ModuleLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldModule, v))
}

// ModuleContains applies the Contains predicate on the "module" field.
func ModuleContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldModule, v))
}

// ModuleHasPrefix applies the HasPrefix predicate on the "module" field.
func ModuleHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldModule, v))
}

// ModuleHasSuffix applies the HasSuffix predicate on the "module" field.
func ModuleHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldModule, v))
}

// ModuleEqualFold applies the EqualFold predicate on the "module" field.
func ModuleEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldModule, v))
}

// ModuleContainsFold applies the ContainsFold predicate on the "module" field.
func ModuleContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldModule, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDContains applies the Contains predicate on the "account_id" field.
func AccountIDContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldAccountID, v))
}

// AccountIDHasPrefix applies the HasPrefix predicate on the "account_id" field.
func AccountIDHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldAccountID, v))
}

// AccountIDHasSuffix applies the HasSuffix predicate on the "account_id" field.
func AccountIDHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldAccountID, v))
}

// AccountIDEqualFold applies the EqualFold predicate on the "account_id" field.
func AccountIDEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldAccountID, v))
}

// AccountIDContainsFold applies the ContainsFold predicate on the "account_id" field.
func AccountIDContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldAccountID, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldCategory, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldAction, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldLevel, v))
}

// LevelContains applies the Contains predicate on the "level" field.
func LevelContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldLevel, v))
}

// LevelHasPrefix applies the HasPrefix predicate on the "level" field.
func LevelHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldLevel, v))
}

// LevelHasSuffix applies the HasSuffix predicate on the "level" field.
func LevelHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldLevel, v))
}

// LevelEqualFold applies the EqualFold predicate on the "level" field.
func LevelEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldLevel, v))
}

// LevelContainsFold applies the ContainsFold predicate on the "level" field.
func LevelContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldLevel, v))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldOutcome, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldSummary, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldSource, v))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldMethod, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldPath, v))
}

// HTTPStatusEQ applies the EQ predicate on the "http_status" field.
func HTTPStatusEQ(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldHTTPStatus, v))
}

// HTTPStatusNEQ applies the NEQ predicate on the "http_status" field.
func HTTPStatusNEQ(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldHTTPStatus, v))
}

// HTTPStatusIn applies the In predicate on the "http_status" field.
func HTTPStatusIn(vs ...int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldHTTPStatus, vs...))
}

// HTTPStatusNotIn applies the NotIn predicate on the "http_status" field.
func HTTPStatusNotIn(vs ...int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldHTTPStatus, vs...))
}

// HTTPStatusGT applies the GT predicate on the "http_status" field.
func HTTPStatusGT(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldHTTPStatus, v))
}

// HTTPStatusGTE applies the GTE predicate on the "http_status" field.
func HTTPStatusGTE(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldHTTPStatus, v))
}

// HTTPStatusLT applies the LT predicate on the "http_status" field.
func HTTPStatusLT(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldHTTPStatus, v))
}

// HTTPStatusLTE applies the LTE predicate on the "http_status" field.
func HTTPStatusLTE(v int) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldHTTPStatus, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldDurationMs, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldRequestID, v))
}

// DetailEQ applies the EQ predicate on the "detail" field.
func DetailEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldDetail, v))
}

// DetailNEQ applies the NEQ predicate on the "detail" field.
func DetailNEQ(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldDetail, v))
}

// DetailIn applies the In predicate on the "detail" field.
func DetailIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldDetail, vs...))
}

// DetailNotIn applies the NotIn predicate on the "detail" field.
func DetailNotIn(vs ...string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldDetail, vs...))
}

// DetailGT applies the GT predicate on the "detail" field.
func DetailGT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldDetail, v))
}

// DetailGTE applies the GTE predicate on the "detail" field.
func DetailGTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldDetail, v))
}

// DetailLT applies the LT predicate on the "detail" field.
func DetailLT(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldDetail, v))
}

// DetailLTE applies the LTE predicate on the "detail" field.
func DetailLTE(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldDetail, v))
}

// DetailContains applies the Contains predicate on the "detail" field.
func DetailContains(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContains(FieldDetail, v))
}

// DetailHasPrefix applies the HasPrefix predicate on the "detail" field.
func DetailHasPrefix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasPrefix(FieldDetail, v))
}

// DetailHasSuffix applies the HasSuffix predicate on the "detail" field.
func DetailHasSuffix(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldHasSuffix(FieldDetail, v))
}

// DetailEqualFold applies the EqualFold predicate on the "detail" field.
func DetailEqualFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEqualFold(FieldDetail, v))
}

// DetailContainsFold applies the ContainsFold predicate on the "detail" field.
func DetailContainsFold(v string) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldContainsFold(FieldDetail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ActivityLog {
	return predicate.ActivityLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ActivityLog) predicate.ActivityLog {
	return predicate.ActivityLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ActivityLog) predicate.ActivityLog {
	return predicate.ActivityLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ActivityLog) predicate.ActivityLog {
	return predicate.ActivityLog(sql.NotPredicates(p))
}
