// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActivityLogsColumns holds the columns for the "activity_logs" table.
	ActivityLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "module", Type: field.TypeString, Size: 64},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "category", Type: field.TypeString, Size: 64},
		{Name: "action", Type: field.TypeString, Size: 128},
		{Name: "level", Type: field.TypeString, Size: 16},
		{Name: "outcome", Type: field.TypeString, Size: 16},
		{Name: "summary", Type: field.TypeString, Size: 500},
		{Name: "source", Type: field.TypeString, Size: 32},
		{Name: "method", Type: field.TypeString, Size: 16, Default: ""},
		{Name: "path", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "http_status", Type: field.TypeInt, Default: 0},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "request_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "detail", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ActivityLogsTable holds the schema information for the "activity_logs" table.
	ActivityLogsTable = &schema.Table{
		Name:       "activity_logs",
		Columns:    ActivityLogsColumns,
		PrimaryKey: []*schema.Column{ActivityLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "activitylog_module_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_module_account_id_category_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[3], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_module_account_id_level_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[5], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_request_id",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[13]},
			},
		},
	}
	// MailboxHiddenMessagesColumns holds the columns for the "mailbox_hidden_messages" table.
	MailboxHiddenMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "generation", Type: field.TypeString, Size: 128},
		{Name: "alias", Type: field.TypeString, Size: 320},
		{Name: "uid", Type: field.TypeUint64},
	}
	// MailboxHiddenMessagesTable holds the schema information for the "mailbox_hidden_messages" table.
	MailboxHiddenMessagesTable = &schema.Table{
		Name:       "mailbox_hidden_messages",
		Columns:    MailboxHiddenMessagesColumns,
		PrimaryKey: []*schema.Column{MailboxHiddenMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxhiddenmessage_account_id_generation_alias_uid",
				Unique:  true,
				Columns: []*schema.Column{MailboxHiddenMessagesColumns[1], MailboxHiddenMessagesColumns[2], MailboxHiddenMessagesColumns[3], MailboxHiddenMessagesColumns[4]},
			},
			{
				Name:    "mailboxhiddenmessage_account_id_generation_uid",
				Unique:  false,
				Columns: []*schema.Column{MailboxHiddenMessagesColumns[1], MailboxHiddenMessagesColumns[2], MailboxHiddenMessagesColumns[4]},
			},
		},
	}
	// MailboxMessagesColumns holds the columns for the "mailbox_messages" table.
	MailboxMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "generation", Type: field.TypeString, Size: 128},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "aliases", Type: field.TypeJSON},
		{Name: "from_address", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "subject", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "message_date", Type: field.TypeFloat64},
		{Name: "text", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "safe_html", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "codes", Type: field.TypeJSON},
		{Name: "partner_codes", Type: field.TypeJSON},
	}
	// MailboxMessagesTable holds the schema information for the "mailbox_messages" table.
	MailboxMessagesTable = &schema.Table{
		Name:       "mailbox_messages",
		Columns:    MailboxMessagesColumns,
		PrimaryKey: []*schema.Column{MailboxMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxmessage_account_id_generation_uid",
				Unique:  true,
				Columns: []*schema.Column{MailboxMessagesColumns[1], MailboxMessagesColumns[2], MailboxMessagesColumns[3]},
			},
			{
				Name:    "mailboxmessage_account_id_generation_message_date",
				Unique:  false,
				Columns: []*schema.Column{MailboxMessagesColumns[1], MailboxMessagesColumns[2], MailboxMessagesColumns[7]},
			},
		},
	}
	// MailboxSyncStatesColumns holds the columns for the "mailbox_sync_states" table.
	MailboxSyncStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "key", Type: field.TypeString, Size: 64},
		{Name: "status", Type: field.TypeJSON},
		{Name: "highest_uid", Type: field.TypeUint64, Default: 0},
		{Name: "allowed_aliases", Type: field.TypeJSON},
	}
	// MailboxSyncStatesTable holds the schema information for the "mailbox_sync_states" table.
	MailboxSyncStatesTable = &schema.Table{
		Name:       "mailbox_sync_states",
		Columns:    MailboxSyncStatesColumns,
		PrimaryKey: []*schema.Column{MailboxSyncStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxsyncstate_account_id_key",
				Unique:  true,
				Columns: []*schema.Column{MailboxSyncStatesColumns[1], MailboxSyncStatesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActivityLogsTable,
		MailboxHiddenMessagesTable,
		MailboxMessagesTable,
		MailboxSyncStatesTable,
	}
)

func init() {
}
