// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ActivityLogsColumns holds the columns for the "activity_logs" table.
	ActivityLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "module", Type: field.TypeString, Size: 64},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "category", Type: field.TypeString, Size: 64},
		{Name: "action", Type: field.TypeString, Size: 128},
		{Name: "level", Type: field.TypeString, Size: 16},
		{Name: "outcome", Type: field.TypeString, Size: 16},
		{Name: "summary", Type: field.TypeString, Size: 500},
		{Name: "source", Type: field.TypeString, Size: 32},
		{Name: "method", Type: field.TypeString, Size: 16, Default: ""},
		{Name: "path", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "http_status", Type: field.TypeInt, Default: 0},
		{Name: "duration_ms", Type: field.TypeInt64, Default: 0},
		{Name: "request_id", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "detail", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ActivityLogsTable holds the schema information for the "activity_logs" table.
	ActivityLogsTable = &schema.Table{
		Name:       "activity_logs",
		Columns:    ActivityLogsColumns,
		PrimaryKey: []*schema.Column{ActivityLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "activitylog_module_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_module_account_id_category_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[3], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_module_account_id_level_created_at",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[1], ActivityLogsColumns[2], ActivityLogsColumns[5], ActivityLogsColumns[16]},
			},
			{
				Name:    "activitylog_request_id",
				Unique:  false,
				Columns: []*schema.Column{ActivityLogsColumns[13]},
			},
		},
	}
	// AuthAPITokensColumns holds the columns for the "auth_api_tokens" table.
	AuthAPITokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Size: 64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "token_prefix", Type: field.TypeString, Size: 20},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// AuthAPITokensTable holds the schema information for the "auth_api_tokens" table.
	AuthAPITokensTable = &schema.Table{
		Name:       "auth_api_tokens",
		Columns:    AuthAPITokensColumns,
		PrimaryKey: []*schema.Column{AuthAPITokensColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authapitoken_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuthAPITokensColumns[1], AuthAPITokensColumns[5]},
			},
		},
	}
	// AuthLoginEventsColumns holds the columns for the "auth_login_events" table.
	AuthLoginEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "username", Type: field.TypeString, Size: 64},
		{Name: "outcome", Type: field.TypeString, Size: 16},
		{Name: "reason", Type: field.TypeString, Size: 64, Default: ""},
		{Name: "ip_address", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuthLoginEventsTable holds the schema information for the "auth_login_events" table.
	AuthLoginEventsTable = &schema.Table{
		Name:       "auth_login_events",
		Columns:    AuthLoginEventsColumns,
		PrimaryKey: []*schema.Column{AuthLoginEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authloginevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuthLoginEventsColumns[7]},
			},
			{
				Name:    "authloginevent_username_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuthLoginEventsColumns[2], AuthLoginEventsColumns[7]},
			},
		},
	}
	// AuthSessionsColumns holds the columns for the "auth_sessions" table.
	AuthSessionsColumns = []*schema.Column{
		{Name: "token_hash", Type: field.TypeString, Size: 64},
		{Name: "user_id", Type: field.TypeInt64},
		{Name: "ip_address", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "last_seen_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
	}
	// AuthSessionsTable holds the schema information for the "auth_sessions" table.
	AuthSessionsTable = &schema.Table{
		Name:       "auth_sessions",
		Columns:    AuthSessionsColumns,
		PrimaryKey: []*schema.Column{AuthSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authsession_user_id_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AuthSessionsColumns[1], AuthSessionsColumns[6]},
			},
		},
	}
	// AuthUsersColumns holds the columns for the "auth_users" table.
	AuthUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "must_change_password", Type: field.TypeBool, Default: false},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// AuthUsersTable holds the schema information for the "auth_users" table.
	AuthUsersTable = &schema.Table{
		Name:       "auth_users",
		Columns:    AuthUsersColumns,
		PrimaryKey: []*schema.Column{AuthUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "authuser_username",
				Unique:  true,
				Columns: []*schema.Column{AuthUsersColumns[1]},
			},
		},
	}
	// MailAliasAppStatesColumns holds the columns for the "mail_alias_app_states" table.
	MailAliasAppStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "alias", Type: field.TypeString, Size: 320},
		{Name: "app_key", Type: field.TypeString, Size: 64},
		{Name: "status", Type: field.TypeString, Size: 24},
		{Name: "detected_at", Type: field.TypeTime, Nullable: true},
		{Name: "detected_uid", Type: field.TypeUint64, Default: 0},
		{Name: "detected_subject", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "detected_sender", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "confirmed_uid", Type: field.TypeUint64, Default: 0},
		{Name: "confirmed_subject", Type: field.TypeString, Size: 500, Default: ""},
		{Name: "confirmed_sender", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MailAliasAppStatesTable holds the schema information for the "mail_alias_app_states" table.
	MailAliasAppStatesTable = &schema.Table{
		Name:       "mail_alias_app_states",
		Columns:    MailAliasAppStatesColumns,
		PrimaryKey: []*schema.Column{MailAliasAppStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailaliasappstate_account_id_alias_app_key",
				Unique:  true,
				Columns: []*schema.Column{MailAliasAppStatesColumns[1], MailAliasAppStatesColumns[2], MailAliasAppStatesColumns[3]},
			},
			{
				Name:    "mailaliasappstate_account_id_status_updated_at",
				Unique:  false,
				Columns: []*schema.Column{MailAliasAppStatesColumns[1], MailAliasAppStatesColumns[4], MailAliasAppStatesColumns[14]},
			},
		},
	}
	// MailboxHiddenMessagesColumns holds the columns for the "mailbox_hidden_messages" table.
	MailboxHiddenMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "generation", Type: field.TypeString, Size: 128},
		{Name: "alias", Type: field.TypeString, Size: 320},
		{Name: "uid", Type: field.TypeUint64},
	}
	// MailboxHiddenMessagesTable holds the schema information for the "mailbox_hidden_messages" table.
	MailboxHiddenMessagesTable = &schema.Table{
		Name:       "mailbox_hidden_messages",
		Columns:    MailboxHiddenMessagesColumns,
		PrimaryKey: []*schema.Column{MailboxHiddenMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxhiddenmessage_account_id_generation_alias_uid",
				Unique:  true,
				Columns: []*schema.Column{MailboxHiddenMessagesColumns[1], MailboxHiddenMessagesColumns[2], MailboxHiddenMessagesColumns[3], MailboxHiddenMessagesColumns[4]},
			},
			{
				Name:    "mailboxhiddenmessage_account_id_generation_uid",
				Unique:  false,
				Columns: []*schema.Column{MailboxHiddenMessagesColumns[1], MailboxHiddenMessagesColumns[2], MailboxHiddenMessagesColumns[4]},
			},
		},
	}
	// MailboxMessagesColumns holds the columns for the "mailbox_messages" table.
	MailboxMessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "generation", Type: field.TypeString, Size: 128},
		{Name: "uid", Type: field.TypeUint64},
		{Name: "aliases", Type: field.TypeJSON},
		{Name: "from_address", Type: field.TypeString, Size: 1000, Default: ""},
		{Name: "subject", Type: field.TypeString, Size: 2000, Default: ""},
		{Name: "message_date", Type: field.TypeFloat64},
		{Name: "text", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "safe_html", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "codes", Type: field.TypeJSON},
		{Name: "partner_codes", Type: field.TypeJSON},
	}
	// MailboxMessagesTable holds the schema information for the "mailbox_messages" table.
	MailboxMessagesTable = &schema.Table{
		Name:       "mailbox_messages",
		Columns:    MailboxMessagesColumns,
		PrimaryKey: []*schema.Column{MailboxMessagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxmessage_account_id_generation_uid",
				Unique:  true,
				Columns: []*schema.Column{MailboxMessagesColumns[1], MailboxMessagesColumns[2], MailboxMessagesColumns[3]},
			},
			{
				Name:    "mailboxmessage_account_id_generation_message_date",
				Unique:  false,
				Columns: []*schema.Column{MailboxMessagesColumns[1], MailboxMessagesColumns[2], MailboxMessagesColumns[7]},
			},
		},
	}
	// MailboxSyncStatesColumns holds the columns for the "mailbox_sync_states" table.
	MailboxSyncStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString, Size: 64, Default: "default"},
		{Name: "key", Type: field.TypeString, Size: 64},
		{Name: "status", Type: field.TypeJSON},
		{Name: "highest_uid", Type: field.TypeUint64, Default: 0},
		{Name: "allowed_aliases", Type: field.TypeJSON},
	}
	// MailboxSyncStatesTable holds the schema information for the "mailbox_sync_states" table.
	MailboxSyncStatesTable = &schema.Table{
		Name:       "mailbox_sync_states",
		Columns:    MailboxSyncStatesColumns,
		PrimaryKey: []*schema.Column{MailboxSyncStatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "mailboxsyncstate_account_id_key",
				Unique:  true,
				Columns: []*schema.Column{MailboxSyncStatesColumns[1], MailboxSyncStatesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ActivityLogsTable,
		AuthAPITokensTable,
		AuthLoginEventsTable,
		AuthSessionsTable,
		AuthUsersTable,
		MailAliasAppStatesTable,
		MailboxHiddenMessagesTable,
		MailboxMessagesTable,
		MailboxSyncStatesTable,
	}
)

func init() {
}
